### ISSUE TITLE
Combine arm64 and amd64 container releases under a single tag

### ISSUE THREAD

**Issue by jgresham** [erigontech/erigon#10023]
# Rationale

Combine builds under one tag. Docker automatically determines the image to pull based on the local arch.
(erigon containers)
![Screenshot 2024-04-22 at 4 14 30 PM](https://github.com/ledgerwatch/erigon/assets/3721291/b264a277-2d80-41a1-a8e1-3ef9b0be781d)
(geth's with combined arch)
![Screenshot 2024-04-22 at 4 13 54 PM](https://github.com/ledgerwatch/erigon/assets/3721291/60276aae-a6ba-44cd-91af-ae98da04a5fa)

Why should this feature exist?
Easier for users, less docs required, less confusion and users reporting false errors by running default image on arm64 platform
What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Pushing to dockerhub arm64 container using the same version tag as the amd64 container. Maybe `docker build ... --platform` flag could help too.
Are you willing to implement this feature?
Yes, but likely better someone with access to ci/cd controls.

**Comment by awskii** [comment]
Hey @jgresham, thank you for your proposal.
@yperbasis, please take a look.

**Comment by lystopad** [comment]
@jgresham , hi

Thank you for your idea.

Our release workflow modified and for the coming 3.0.0 version we will release a single multi-platform docker image which supports following OS/Arch:
- linux/arm64
- linux/amd64
- linux/amd64/v2

Hopefully I will manage my dependency tasks and back-port it to 2.60.x release branch.

Best regards
@lystopad

**Comment by jgresham** [comment]
> @jgresham , hi
> 
> Thank you for your idea.
> 
> Our release workflow modified and for the coming 3.0.0 version we will release a single multi-platform docker image which supports following OS/Arch:
> 
> * linux/arm64
> * linux/amd64
> * linux/amd64/v2
> 
> Hopefully I will manage my dependency tasks and back-port it to 2.60.x release branch.
> 
> Best regards @lystopad

great, thank you!
