### ISSUE TITLE
Caplin: to not use `temp` dir for temporary database

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#10087]
Reason: 
- `temp` folder designed for `bufio` (by ETL) - it makes folder friendly for symlinking to HDD
- temporary database may be > 50Gb in size (because Caplin doesn't support `--sync.loop.block.limit` and loading all blocks of first sync cycle to temporary db). And temporary db is `mdbx` - very HDD-unfriendly thing (sequential PageFaults) - if we don't enable READAHEAD flag for this DB.

**Comment by Giulio2002** [comment]
but we use for ETL.

**Comment by AskAlexSharov** [comment]
> but we use for ETL. We also use it for the temporary forkchoice database too but that is also just Dump/ReadAll

For small db - it's ok. but i saw some DB > 50Gb. Such db (> RAM) will be crazy slow on HDD.
