### ISSUE TITLE
Potentially switch to GitHub large runners for faster CI

### ISSUE THREAD

**Issue by yperbasis** [erigontech/erigon#10345]
With the upgrade to https://github.com/enterprises/erigon-ag we can use large runners

**Comment by michelemodolo** [comment]
@yperbasis 
DevOps team doesn't have access to erigontech org settings so they cannot work on org-wide runners. 
DevOps team doesn't have access to erigon repo settings so they cannot work on repo-wide runners. 

So I'm removing the "devops" label from this task and I'm reassigning it to @VBulikov
