### ISSUE TITLE
Update ethereum/tests

### ISSUE THREAD

**Issue by yperbasis** [erigontech/erigon#10928]
Currently `erigon/tests/testdata` (git submodule) points to [v13.1](https://github.com/ethereum/tests/releases/tag/v13.1) of ethereum/tests. (ethereum/tests is an older test suite compared to [execution-spec-tests](https://github.com/ethereum/execution-spec-tests), but still relevant.) Plz update it to the latest release [v13.3](https://github.com/ethereum/tests/releases/tag/v13.3).

Its runners like `TestBlockchain` are protected by `go:build integration`, so `make test` doesn't run the tests by default. To trigger a run manually call something like
```
go test ./tests -tags integration -timeout 40m
```

**Comment by yperbasis** [comment]
https://github.com/ethereum/tests/releases/tag/v14.0 has been just released - please upgrade to that.

**Comment by sudeepdino008** [comment]
create eip-7610 inclusion issue - https://github.com/ledgerwatch/erigon/issues/11075
