### ISSUE TITLE
Add "block production" GitHub CI 

### ISSUE THREAD

**Issue by dvovk** [erigontech/erigon#10943]
User reports that PRs often break block production. 
Discord link: https://discord.com/channels/687972960811745322/886550095749873666/1256174265296879626

**Comment by AskAlexSharov** [comment]
maybe related to https://github.com/ledgerwatch/erigon/issues/10313

**Comment by yperbasis** [comment]
From https://discord.com/channels/687972960811745322/886550095749873666/1254785984973766687:
Barnabas — 06/24/2024 3:11 PM
"Found the commit that broke it:

Working commit: main-6d80c0f
Breaking commit: main-5327cc0
I would highly recommend to try to integrate assertoor with kurtosis  in your CI workflow, as these kinda probelms could be caught in the PR itself. 
https://github.com/ethpandaops/kurtosis-assertoor-github-action"

**Comment by sudeepdino008** [comment]
https://github.com/erigontech/erigon/pull/11464
