### ISSUE TITLE
`milestoneId doesn't exist in Heimdall` when running Polygon with Astrid

### ISSUE THREAD

**Issue by shohamc1** [erigontech/erigon#10959]

**Comment by shohamc1** [comment]
Issue does not reoccur as of [e6cda71](https://github.com/erigontech/erigon/commit/e6cda71882f3e23f8a03e8e797fa906f13a60f76).

**Comment by taratorio** [comment]
Mark saw this again:
```[EROR] [08-27|09:10:59.415] [2/6 PolygonSync] stopping node          err="milestoneId doesn't exist in Heimdall: number 300096"```

**Comment by taratorio** [comment]
@shohamc1 maybe there is a race condition:
- heimdall keeps only last 100 milestones at a time (like a sliding window)
- `FetchFirstMilestoneNum` talks to heimdall and returns 130 as the first milestone num we should fetch (so it keeps 130-230 milestones)
- by the time we do the request to fetch milestone num 130 heimdall has dropped (heimdall has moved to 131-231 milestones)
- seems like a very rare and unfortunate case but we do no need to handle it somehow

**Comment by taratorio** [comment]
Actually I started getting this error more frequently as well:
```
EROR[08-27|14:59:09.685] [2/6 PolygonSync] stopping node          err="milestoneId doesn't exist in Heimdall: number 300259"
```

When I checked (pretty quickly after I got the error) milestone `300259` was actually not T-100 (what I thought the bug scenario was in my previous message) but was T (ie the latest milestone id).

So weirdly, `FetchMilestoneCount` has returned `300259` and we've tried to fetch `300259` using `FetchMilestone` but that has returned an error.
