### ISSUE TITLE
Beacon API can not start when using rewards

### ISSUE THREAD

**Issue by jasonyic** [erigontech/erigon#11045]
#### System information

Erigon version: `erigon version 2.60.2-7055c2cb`

OS & Version: Linux

Commit hash: 

Erigon Command (with flags/config):

```
erigon --datadir=/data --chain=holesky --http --http.port=8545 --http.addr=0.0.0.0 --http.api=admin,eth,web3,net --http.corsdomain=* --http.vhosts=* --nat=extip:4.255.42.20 --port=31515 --metrics --metrics.addr=0.0.0.0 --metrics.port=9545 --config=/data/config.toml --db.size.limit=1TB --internalcl=true --maxpeers=300 --caplin.archive=true --beacon.api=beacon,builder,config,debug,events,node,validator,lighthouse,rewards --beacon.api.addr=0.0.0.0 --beacon.api.port=5051 --db.size.limit=1TB --beacon.api.read.timeout=15
```

Consensus Layer:  Caplin

Consensus Layer Command (with flags/config): N/A

Chain/Network: 

#### Expected behaviour
Beacon API should start sucessfully:
```
[INFO] [07-05|09:37:11.251] Beacon API started                       addr=0.0.0.0:5051
```

#### Actual behaviour
Beacon API started not started

```
[EROR] [07-05|10:33:01.808] Failed to set beacon API                 err="unknown endpoint for beacon.api: rewards. known endpoints: beacon, builder, config, debug, events, node, validator, lighthouse"
```

#### Backtrace

````
[backtrace]
````

**Comment by jasonyic** [comment]
rewards is not supported in 2.60.x

**Comment by jasonyic** [comment]
documentation should be update to reflect the missing API

**Comment by Giulio2002** [comment]
ok, no it does support rewards, it under beacon, will update flags description for that - I think it just stayed there and in the readme it should be correct. If you query the endpoints with beacon enabled, it should just work
