### ISSUE TITLE
Stuck at 19800k block with sentry warnings

### ISSUE THREAD

**Issue by kovalishinilya** [erigontech/erigon#11109]
#### System information

Erigon version: 2.60.4-72ab70be

OS & Version: Ubuntu 24.04 LTS

Commit hash:  [72ab70b](https://github.com/ledgerwatch/erigon/commit/72ab70be8b28964a8446e52b7a9975958c6726bf)

Erigon Command (with flags/config): erigon --datadir <datadir> --db.size.limit 4TB --chain mainnet
Consensus Layer:

Consensus Layer Command (with flags/config):

Chain/Network: Mainnet

#### Expected behaviour
sync normally

#### Actual behaviour
no syncing whatsoever
stuck at block 19799999
experiencing sentry warnings
```
WARN[07-10|23:10:22.358] sentry.StatusDataProvider: The canonical chain current header not found in the database. Check the database consistency. Using genesis as a fallback. 
WARN[07-10|23:10:22.358] sentry.StatusDataProvider: The canonical chain current header not found in the database. Check the database consistency. Using genesis as a fallback. 
WARN[07-10|23:10:22.358] sentry.StatusDataProvider: The canonical chain current header not found in the database. Check the database consistency. Using genesis as a fallback. 
WARN[07-10|23:10:22.358] sentry.StatusDataProvider: The canonical chain current header not found in the database. Check the database consistency. Using genesis as a fallback. 
WARN[07-10|23:10:22.358] sentry.StatusDataProvider: The canonical chain current header not found in the database. Check the database consistency. Using genesis as a fallback. 
WARN[07-10|23:10:22.358] sentry.StatusDataProvider: The canonical chain current header not found in the database. Check the database consistency. Using genesis as a fallback. 
WARN[07-10|23:10:22.358] sentry.StatusDataProvider: The canonical chain current header not found in the database. Check the database consistency. Using genesis as a fallback. 
WARN[07-10|23:10:22.358] sentry.StatusDataProvider: The canonical chain current header not found in the database. Check the database consistency. Using genesis as a fallback.
``` 
after these two lines there are just memory and txpool stats
```
[snapshots:download] Stat                blocks=19800k indices=19800k alloc=3.1GB sys=4.8GB
INFO[07-10|23:10:25.230] [txpool] Started 
INFO[07-10|23:13:22.342] [p2p] GoodPeers                          eth68=2 eth66=1 eth67=3
``` 

#### Steps to reproduce the behaviour
restart erigon

**Comment by AskAlexSharov** [comment]
`--internalcl`

**Comment by RickyEsclapon** [comment]
Could someone explain this better? First time trying to run a node and this gave me massive difficulties. Did we do something wrong or what was the cause of this? I was also having the same exact problem on block 19799999

**Comment by AskAlexSharov** [comment]
All Ethereum clients have same architecture: 1 service for Consensus Layer, 1 service for Execution Layer. It's how `The Merge` was implemented/released: https://ethereum.org/en/developers/docs/nodes-and-clients/#client-diversity 
`--internalcl` it's the way to run our CL (Caplin) inside Erigon's process. 

Related with: https://github.com/erigontech/erigon/issues/11251

**Comment by AskAlexSharov** [comment]
@RickyEsclapon did you use https://erigon.gitbook.io/ ?
