### ISSUE TITLE
rename `--prune=minimal` to `--prune=minimal_node`

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11140]
people say: `--prune=minimal` feels like "minimum pruning" 
@Giulio2002 what do you think?

**Comment by Giulio2002** [comment]
who asked that? what is the rationale?

**Comment by Giulio2002** [comment]
I was actually thinking of creating flags: `minimal` and `full` for that lol

**Comment by AskAlexSharov** [comment]
@Giulio2002 i would vote for:
`--minimal`: shortcut for `--prune=hrtcb`
`--full`: shortcut for `--prune=hrtc`
keep `--prune` if somebody like more granular tuning
