### ISSUE TITLE
sentry multi client refactor for astrid

### ISSUE THREAD

**Issue by taratorio** [erigontech/erigon#11183]
Currently we only use 1 sentry in astrid (sentry for eth/68). We need to add support for multiple sentries for 2 reasons:
- to make use of peers only on eth/66 and eth/67
- to stick to erigon's thorax architecture that envisions 1 node connecting to multiple sentries running on other machines

Additionally, Astrid currently uses a mix of `polygon/p2p` for supporting the new astrid polygon specific fetch APIs and also the `p2p/sentry/sentry_multi_client MultiClient` to respond to p2p message that require the node to respond with some data. So when running Astrid both `polygon/p2p Service` (will rename to Connector) and `p2p/sentry/sentry_multi_client MultiClient` need to be run. This caused issues because the `p2p/sentry/sentry_multi_client MultiClient` is coupled with `Hd` and `Bd` structures and the stage loop sync. This problem was addressed with a short term fix in this PR (https://github.com/ledgerwatch/erigon/pull/9957), however ideally we would like to de-couple the `MultiClient` logic from the sync logic that `Hd` and `Bd` data structures impose.

All of this involves a sentry multi client refactor to be done in multiple steps with a separate PR per step:
- [x] https://github.com/erigontech/erigon/issues/11676 - implement a new `MultiClient` in `p2p/sentry` using the multiplexer decorator pattern (silkworm already does that can read for inspiration) where we have a multiplexer MultiClient implement the same SentryClient interface but internally it multiplexes the calls to N sentries
- [x] https://github.com/erigontech/erigon/issues/11676 - use the new `MultiClient` when instantiating Astrid 
- [ ] rename the old `p2p/sentry/sentry_multi_client SentryMultiClient` to `Connector` and move to `eth/p2p` package - this will be the eth p2p connector. This is analogous to how we have a Polygon specific wrapper around sentry with a different API in `polygon/p2p` (might also need to rename the component to Connector in that package as well if not done already)
- [ ] move `MessageListener` from `polygon/p2p` to `p2p/sentry`
- [ ] #11858
- [ ] use the `MessageResponder` in `polygon/p2p Connector`
- [ ] refactor the remaining API of `eth/p2p Connector` to use the `MessageListener` and the new `MultiClient` - this will de-couple the `Hd` and `Bd` (header download and block download structures) from the core sentry multi client code

**Comment by mh0lt** [comment]
This is complete: currently in beta test
