### ISSUE TITLE
gnosis: remove of `chaindata` and `caplin` folders in same time caused long DownloadHistoricalBlocks  

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11187]
After 24 hours i see next in logs: 
```
[INFO] [07-16|02:51:19.035] Node is still syncing... downloading past blocks app=caplin stage=DownloadHistoricalBlocks slot=12508936 blockNumber=31242787 frozenBlocks=34886999 blk/sec=47.1 snapshots=0
```
it's unclear from logs - something goes wrong or just need wait - and at which blockNumber/slot it plans to stop downloading. 

flags: `--caplin.backfilling --caplin.archive --caplin.backfilling.blob`

**Comment by AskAlexSharov** [comment]
`mainnet` node:

```

```
[WARN] [07-22|06:40:40.064] Could not set forkchoice                 app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[WARN] [07-22|06:40:40.064] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[DBUG] [07-22|06:40:40.064] clstage finish                           app=caplin stage=ForkChoice in=2.511556264s next=ListenForForks
[DBUG] [07-22|06:40:40.064] clstage finish                           app=caplin stage=ListenForForks in=4.591µs next=CleanupAndPruning
[DBUG] [07-22|06:40:40.064] clstage finish                           app=caplin stage=CleanupAndPruning in=163.727µs next=SleepForSlot
[DBUG] [07-22|06:40:40.064] sleeping until next slot                 app=caplin stage=SleepForSlot slot=9567202 time=2024-07-22T06:40:47+0000 dur=6.935616146s
[DBUG] [07-22|06:40:47.000] clstage finish                           app=caplin stage=SleepForSlot in=6.935656665s next=CatchUpBlocks
[DBUG] [07-22|06:40:47.056] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:40:47.057] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567201 targetSlot=9567202 requestedSlots=1
[DBUG] [07-22|06:40:48.323] Received blob sidecar via gossip         index=3 size=128KB
[DBUG] [07-22|06:40:48.339] Received blob sidecar via gossip         index=2 size=128KB
[DBUG] [07-22|06:40:48.347] Received block via gossip                slot=9567202
[DBUG] [07-22|06:40:48.347] Block scheduled for later processing     slot=9567202 block=20360344
[DBUG] [07-22|06:40:48.356] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:40:48.386] Received blob sidecar via gossip         index=4 size=128KB
[DBUG] [07-22|06:40:48.546] Received blob sidecar via gossip         index=5 size=128KB
[DBUG] [07-22|06:40:48.637] Received blob sidecar via gossip         index=0 size=128KB
[DBUG] [07-22|06:40:59.951] OnBlock: block is not validated yet      block=0x03561dd63cae2805d6fac5ec4d7b2c360d034167db4706bcab4fbbda795c8bfc
[DBUG] [07-22|06:41:00.126] OnBlock                                  elapsed=183.001035ms
[DBUG] [07-22|06:41:00.127] clstage finish                           app=caplin stage=CatchUpBlocks in=13.126923907s next=CatchUpBlocks
[DBUG] [07-22|06:41:00.132] OnBlock: block is not validated yet      block=0x03561dd63cae2805d6fac5ec4d7b2c360d034167db4706bcab4fbbda795c8bfc
[DBUG] [07-22|06:41:00.132] import operations                        time=3.587µs
[DBUG] [07-22|06:41:00.181] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:41:00.182] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567202 targetSlot=9567203 requestedSlots=1
[DBUG] [07-22|06:41:00.904] Received block via gossip                slot=9567203
[DBUG] [07-22|06:41:00.904] Block scheduled for later processing     slot=9567203 block=20360345
[DBUG] [07-22|06:41:01.186] OnBlock: block is not validated yet      block=0xc026e9600bf0668b2fafcc39aa4f3129d38d37f82a95b484adc4cbbfdb981421
[DBUG] [07-22|06:41:01.303] clstage finish                           app=caplin stage=CatchUpBlocks in=1.17586364s next=ForkChoice
[DBUG] [07-22|06:41:01.310] OnBlock                                  elapsed=126.749714ms
[DBUG] [07-22|06:41:01.310] import operations                        time=1.01µs
[DBUG] [07-22|06:41:01.317] Caplin is sending forkchoice             app=caplin stage=ForkChoice
[WARN] [07-22|06:41:01.404] Could not set forkchoice                 app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[WARN] [07-22|06:41:01.404] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[DBUG] [07-22|06:41:01.404] clstage finish                           app=caplin stage=ForkChoice in=101.355853ms next=ListenForForks
[DBUG] [07-22|06:41:01.404] clstage finish                           app=caplin stage=ListenForForks in=3.435µs next=CleanupAndPruning
[DBUG] [07-22|06:41:01.404] clstage finish                           app=caplin stage=CleanupAndPruning in=206.91µs next=SleepForSlot
[DBUG] [07-22|06:41:01.404] sleeping until next slot                 app=caplin stage=SleepForSlot slot=9567204 time=2024-07-22T06:41:11+0000 dur=9.595121389s
[DBUG] [07-22|06:41:11.000] clstage finish                           app=caplin stage=SleepForSlot in=9.595182593s next=CatchUpBlocks
[DBUG] [07-22|06:41:11.059] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:41:11.060] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567203 targetSlot=9567204 requestedSlots=1
[DBUG] [07-22|06:41:12.393] Received block via gossip                slot=9567204
[DBUG] [07-22|06:41:12.393] Block scheduled for later processing     slot=9567204 block=20360346
[DBUG] [07-22|06:41:12.417] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:41:12.448] Received blob sidecar via gossip         index=2 size=128KB
[DBUG] [07-22|06:41:12.450] Received blob sidecar via gossip         index=4 size=128KB
[DBUG] [07-22|06:41:12.470] Received blob sidecar via gossip         index=3 size=128KB
[DBUG] [07-22|06:41:12.524] Received blob sidecar via gossip         index=5 size=128KB
[DBUG] [07-22|06:41:12.582] Received blob sidecar via gossip         index=0 size=128KB
[DBUG] [07-22|06:41:21.981] OnBlock: block is not validated yet      block=0x3e9ee324c420297ff8a3c2116db9e9fb3827e13387150c97dde32502f03ce828
[DBUG] [07-22|06:41:22.174] OnBlock                                  elapsed=200.175168ms
[DBUG] [07-22|06:41:22.175] clstage finish                           app=caplin stage=CatchUpBlocks in=11.175022182s next=ForkChoice
[DBUG] [07-22|06:41:22.189] OnBlock: block is not validated yet      block=0x3e9ee324c420297ff8a3c2116db9e9fb3827e13387150c97dde32502f03ce828
[DBUG] [07-22|06:41:22.189] import operations                        time=2.893µs
[DBUG] [07-22|06:41:22.218] Caplin is sending forkchoice             app=caplin stage=ForkChoice
[WARN] [07-22|06:41:22.351] Could not set forkchoice                 app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[WARN] [07-22|06:41:22.351] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[DBUG] [07-22|06:41:22.352] clstage finish                           app=caplin stage=ForkChoice in=176.397811ms next=ListenForForks
[DBUG] [07-22|06:41:22.352] clstage finish                           app=caplin stage=ListenForForks in=4.618µs next=CleanupAndPruning
[DBUG] [07-22|06:41:22.352] clstage finish                           app=caplin stage=CleanupAndPruning in=225.463µs next=SleepForSlot
[DBUG] [07-22|06:41:22.352] sleeping until next slot                 app=caplin stage=SleepForSlot slot=9567205 time=2024-07-22T06:41:23+0000 dur=647.642537ms
[DBUG] [07-22|06:41:23.000] clstage finish                           app=caplin stage=SleepForSlot in=648.212176ms next=CatchUpBlocks
[DBUG] [07-22|06:41:23.057] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:41:23.059] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567204 targetSlot=9567205 requestedSlots=1
[DBUG] [07-22|06:41:24.886] Received block via gossip                slot=9567205
[DBUG] [07-22|06:41:24.886] Block scheduled for later processing     slot=9567205 block=20360347
[DBUG] [07-22|06:41:24.918] OnBlock: block is not validated yet      block=0x2b4d357e2d54421bfdb71ae75f25f1721a21510c295210ca38d9499c333e3510
[DBUG] [07-22|06:41:25.075] OnBlock                                  elapsed=162.825044ms
[DBUG] [07-22|06:41:25.075] import operations                        time=1.141µs
[DBUG] [07-22|06:41:25.079] clstage finish                           app=caplin stage=CatchUpBlocks in=2.079075145s next=ForkChoice
[DBUG] [07-22|06:41:25.091] Caplin is sending forkchoice             app=caplin stage=ForkChoice
[WARN] [07-22|06:41:25.175] Could not set forkchoice                 app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[WARN] [07-22|06:41:25.175] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[DBUG] [07-22|06:41:25.175] clstage finish                           app=caplin stage=ForkChoice in=95.456346ms next=ListenForForks
[DBUG] [07-22|06:41:25.175] clstage finish                           app=caplin stage=ListenForForks in=7.685µs next=CleanupAndPruning
[DBUG] [07-22|06:41:25.175] clstage finish                           app=caplin stage=CleanupAndPruning in=161.422µs next=SleepForSlot
[DBUG] [07-22|06:41:25.175] sleeping until next slot                 app=caplin stage=SleepForSlot slot=9567206 time=2024-07-22T06:41:35+0000 dur=9.824174657s
[DBUG] [07-22|06:41:35.000] clstage finish                           app=caplin stage=SleepForSlot in=9.824719939s next=CatchUpBlocks
[DBUG] [07-22|06:41:35.052] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:41:35.052] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567205 targetSlot=9567206 requestedSlots=1
[DBUG] [07-22|06:41:36.561] Received block via gossip                slot=9567206
[DBUG] [07-22|06:41:36.561] Block scheduled for later processing     slot=9567206 block=20360348
[DBUG] [07-22|06:41:36.567] Received blob sidecar via gossip         index=5 size=128KB
[DBUG] [07-22|06:41:36.600] Received blob sidecar via gossip         index=2 size=128KB
[DBUG] [07-22|06:41:36.602] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:41:36.616] Received blob sidecar via gossip         index=3 size=128KB
[DBUG] [07-22|06:41:36.624] Received blob sidecar via gossip         index=4 size=128KB
[DBUG] [07-22|06:41:36.843] Received blob sidecar via gossip         index=0 size=128KB
[DBUG] [07-22|06:41:43.890] OnBlock: block is not validated yet      block=0x493a178e590c236a3be6843a3e4c22384d122b5311ad455230a8a6ec7dc81342
[DBUG] [07-22|06:41:44.057] OnBlock                                  elapsed=174.986062ms
[DBUG] [07-22|06:41:44.058] clstage finish                           app=caplin stage=CatchUpBlocks in=9.057851079s next=ForkChoice
[DBUG] [07-22|06:41:44.061] OnBlock: block is not validated yet      block=0x493a178e590c236a3be6843a3e4c22384d122b5311ad455230a8a6ec7dc81342
[DBUG] [07-22|06:41:44.061] import operations                        time=3.494µs
[DBUG] [07-22|06:41:44.075] Caplin is sending forkchoice             app=caplin stage=ForkChoice
[WARN] [07-22|06:41:44.193] Could not set forkchoice                 app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[WARN] [07-22|06:41:44.193] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[DBUG] [07-22|06:41:44.193] clstage finish                           app=caplin stage=ForkChoice in=134.615001ms next=ListenForForks
[DBUG] [07-22|06:41:44.193] clstage finish                           app=caplin stage=ListenForForks in=3.712µs next=CleanupAndPruning
[DBUG] [07-22|06:41:44.193] clstage finish                           app=caplin stage=CleanupAndPruning in=162.615µs next=SleepForSlot
[DBUG] [07-22|06:41:44.193] sleeping until next slot                 app=caplin stage=SleepForSlot slot=9567207 time=2024-07-22T06:41:47+0000 dur=2.806421773s
[DBUG] [07-22|06:41:45.051] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:41:47.000] clstage finish                           app=caplin stage=SleepForSlot in=2.806872163s next=CatchUpBlocks
[DBUG] [07-22|06:41:47.056] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:41:47.057] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567206 targetSlot=9567207 requestedSlots=1
[DBUG] [07-22|06:41:48.651] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:41:48.655] Received block via gossip                slot=9567207
[DBUG] [07-22|06:41:48.655] Block scheduled for later processing     slot=9567207 block=20360349
[DBUG] [07-22|06:41:48.805] Received blob sidecar via gossip         index=0 size=128KB
[DBUG] [07-22|06:41:53.735] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:41:59.261] OnBlock: block is not validated yet      block=0xfece54fe9b6607940cf6953730b29c566e4c440cf7e9edd86057303ce1a5edab
[DBUG] [07-22|06:41:59.461] OnBlock                                  elapsed=201.874636ms
[DBUG] [07-22|06:41:59.461] import operations                        time=1.877µs
[DBUG] [07-22|06:41:59.463] OnBlock: block is not validated yet      block=0xfece54fe9b6607940cf6953730b29c566e4c440cf7e9edd86057303ce1a5edab
[DBUG] [07-22|06:41:59.465] clstage finish                           app=caplin stage=CatchUpBlocks in=12.464286198s next=CatchUpBlocks
[DBUG] [07-22|06:41:59.518] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:41:59.519] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567207 targetSlot=9567208 requestedSlots=1
[DBUG] [07-22|06:41:59.762] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:42:00.979] Received block via gossip                slot=9567208
[DBUG] [07-22|06:42:00.987] Block scheduled for later processing     slot=9567208 block=20360350
[DBUG] [07-22|06:42:04.058] OnBlock: block is not validated yet      block=0x703b33162f967e5b941fddff6ef8a9d1ecf9c4c7ce13c338068d63437267ed45
[DBUG] [07-22|06:42:04.220] clstage finish                           app=caplin stage=CatchUpBlocks in=4.75570755s next=ForkChoice
[DBUG] [07-22|06:42:04.235] OnBlock                                  elapsed=185.190103ms
[DBUG] [07-22|06:42:04.235] import operations                        time=1.28µs
[DBUG] [07-22|06:42:06.364] Caplin is sending forkchoice             app=caplin stage=ForkChoice
[WARN] [07-22|06:42:08.802] Could not set forkchoice                 app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[WARN] [07-22|06:42:08.802] error executing clstage                  app=caplin stage=ForkChoice err="execution Client RPC failed to retrieve ForkChoiceUpdate response, err: too far unwind. requested=20319999, minAllowed=20328548"
[DBUG] [07-22|06:42:08.802] clstage finish                           app=caplin stage=ForkChoice in=4.581714416s next=ListenForForks
[DBUG] [07-22|06:42:08.802] clstage finish                           app=caplin stage=ListenForForks in=4.857µs next=CleanupAndPruning
[DBUG] [07-22|06:42:08.803] clstage finish                           app=caplin stage=CleanupAndPruning in=228.03µs next=SleepForSlot
[DBUG] [07-22|06:42:08.803] sleeping until next slot                 app=caplin stage=SleepForSlot slot=9567209 time=2024-07-22T06:42:11+0000 dur=2.196902724s

[DBUG] [07-22|06:42:11.000] clstage finish                           app=caplin stage=SleepForSlot in=2.197755556s next=CatchUpBlocks
[DBUG] [07-22|06:42:11.056] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:42:11.057] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567208 targetSlot=9567209 requestedSlots=1
[DBUG] [07-22|06:42:13.247] Received block via gossip                slot=9567209
[DBUG] [07-22|06:42:13.247] Block scheduled for later processing     slot=9567209 block=20360351
[DBUG] [07-22|06:42:13.265] Received blob sidecar via gossip         index=2 size=128KB
[DBUG] [07-22|06:42:13.279] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:42:13.286] Received blob sidecar via gossip         index=3 size=128KB
[DBUG] [07-22|06:42:13.389] Received blob sidecar via gossip         index=0 size=128KB
[DBUG] [07-22|06:42:15.863] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:42:24.883] Received block via gossip                slot=9567210
[DBUG] [07-22|06:42:24.883] Block scheduled for later processing     slot=9567210 block=20360352
[DBUG] [07-22|06:42:24.890] Received blob sidecar via gossip         index=2 size=128KB
[DBUG] [07-22|06:42:24.904] Received blob sidecar via gossip         index=1 size=128KB
[DBUG] [07-22|06:42:25.138] Received blob sidecar via gossip         index=0 size=128KB
[DBUG] [07-22|06:42:28.887] OnBlock: block is not validated yet      block=0x11eebadc287d9803aaee2cbc14d73b9faf830465b1198d64ac7bc994bd4c4fb0
[DBUG] [07-22|06:42:29.075] OnBlock                                  elapsed=195.646107ms
[DBUG] [07-22|06:42:29.076] clstage finish                           app=caplin stage=CatchUpBlocks in=18.07491649s next=CatchUpBlocks
[DBUG] [07-22|06:42:29.083] OnBlock: block is not validated yet      block=0x11eebadc287d9803aaee2cbc14d73b9faf830465b1198d64ac7bc994bd4c4fb0
[DBUG] [07-22|06:42:29.083] import operations                        time=2.212µs
[DBUG] [07-22|06:42:29.133] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:42:29.134] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567209 targetSlot=9567210 requestedSlots=1
[DBUG] [07-22|06:42:33.484] Received block via gossip                slot=9567090
[DBUG] [07-22|06:42:33.484] Block scheduled for later processing     slot=9567090 block=20360232
[DBUG] [07-22|06:42:33.511] import operations                        time=2.138µs
[DBUG] [07-22|06:42:35.895] Received block via gossip                slot=9567211
[DBUG] [07-22|06:42:35.895] Block scheduled for later processing     slot=9567211 block=20360353
[DBUG] [07-22|06:42:38.768] [downloader] Collecting...               from=20360353 to=20360353 len=1
[DBUG] [07-22|06:42:38.768] [downloader] posAnchor is nil
[DBUG] [07-22|06:42:39.045] OnBlock: block is not validated yet      block=0xb26803ad44d7072e61f83bce1d0d0e94ed299e9c89b73fc887f8ffb3c25c8632
[DBUG] [07-22|06:42:39.159] OnBlock                                  elapsed=118.776602ms
[DBUG] [07-22|06:42:39.160] clstage finish                           app=caplin stage=CatchUpBlocks in=10.084232487s next=CatchUpBlocks
[DBUG] [07-22|06:42:39.161] OnBlock: block is not validated yet      block=0xb26803ad44d7072e61f83bce1d0d0e94ed299e9c89b73fc887f8ffb3c25c8632
[DBUG] [07-22|06:42:39.161] import operations                        time=951ns
[DBUG] [07-22|06:42:39.162] OnBlock: block is not validated yet      block=0xbb07ccb60da70b0155bbebb661d94687e993352ab9a8204105a1fa07ef5f00e5
[DBUG] [07-22|06:42:39.211] [db] open                                label=inMem sizeLimit=512MB pageSize=4096
[DBUG] [07-22|06:42:39.212] waiting for blocks...                    app=caplin stage=CatchUpBlocks seenSlot=9567210 targetSlot=9567211 requestedSlots=1
[DBUG] [07-22|06:42:39.250] OnBlock                                  elapsed=88.559013ms
[DBUG] [07-22|06:42:39.250] import operations                        time=1.111µs
```

**Comment by AskAlexSharov** [comment]
seems removal of latest step of state files helped

**Comment by Giulio2002** [comment]
I think that it is probably expected and normal behaviour, i may change it in the future but it is because you are running caplin archive if anything
