### ISSUE TITLE
add `MdbxWriteMap` field to `txpoolcfg.Config` 

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11203]
- and corresponding cli flag to `cmd/txpool/main.go`
- and set it in `cmd/utils/flags.go:setTxPool(ctx, cfg)`
- and use it in `AllComponents`

Additional: review `DeprecatedTxPoolConfig` class and create github issue - what to do with it - how to migrate to `txpoolcfg.Config`

**Comment by JkLondon** [comment]
https://github.com/erigontech/erigon/issues/11240
