### ISSUE TITLE
Multiple release of the same client version

### ISSUE THREAD

**Issue by eenagy** [erigontech/erigon#11212]
Erigon version 2.60.4 was released last week but was rereleased just two hours ago, again. This isn't the first time an update has occurred without any explanation. (Or maybe I didn't find it)

I'm currently focusing on reproducible builds, so this is troubling. I have encountered a similar issue where some clients needed to update their version due to their build process breaking a current build, but this was addressed by rereleasing it as a new version. Could someone please explain why this is happening?

**Comment by AskAlexSharov** [comment]
@eenagy  `version 2.60.4` - do you mean: git tag or docker image version or something else?
i see git tag was created last week: https://github.com/ledgerwatch/erigon/tags
and release was created hours ago: https://github.com/ledgerwatch/erigon/releases - but it didn't modify git tag

if by `version 2.60.4` you mean "github releases" - then how do you depend on releases? is it git-web-hooks? or something else?

**Comment by eenagy** [comment]
@AskAlexSharov I depend on `https://github.com/ledgerwatch/erigon/releases` through tarballs. 
Sorry, I think this is my mistake, let me recheck on my end. The tarballs hash seems to be the same, I think I have been too hasty to open this issue.
