### ISSUE TITLE
Migration from DeprecatedTxPoolConfig to txpool.Config

### ISSUE THREAD

**Issue by JkLondon** [erigontech/erigon#11240]
# Rationale
we should migrate from DeprecatedTxPoolConfig to txpool.Config.

let's see values of dep config
```
type DeprecatedTxPoolConfig struct {
	Disable  bool
	Locals   []common.Address // Addresses that should be treated by default as local
	NoLocals bool             // Whether local transaction handling should be disabled

	PriceLimit uint64 // Minimum gas price to enforce for acceptance into the pool
	PriceBump  uint64 // Minimum price bump percentage to replace an already existing transaction (nonce)

	AccountSlots uint64 // Number of executable transaction slots guaranteed per account
	GlobalSlots  uint64 // Maximum number of executable transaction slots for all accounts
	AccountQueue uint64 // Maximum number of non-executable transaction slots permitted per account
	GlobalQueue  uint64 // Maximum number of non-executable transaction slots for all accounts

	GlobalBaseFeeQueue uint64 // Maximum number of non-executable transaction slots for all accounts

	Lifetime      time.Duration // Maximum amount of time non-executable transaction are queued
	StartOnInit   bool
	TracedSenders []string // List of senders for which txn pool should print out debugging info
	CommitEvery   time.Duration
}
```
Disable disables TxPool at all. Should be migrated to txpool.Config.
Locals is described bellow. Also should be migrated to txpool.Config.

`AccountQueue uint64 // Maximum number of non-executable transaction slots permitted per account`
`Lifetime time.Duration // Maximum amount of time non-executable transaction are queued`
`StartOnInit   bool`
are not used anywhere. maybe it's wrong.

Rest of fields are already in txpool.Config. Easy to move.

# Important note
The only problem is that this config is setted from TOML file and erasing old config requires to change .toml confs for all of users

**Comment by AskAlexSharov** [comment]
done
