### ISSUE TITLE
Add warning - no CL connected

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11251]
Add geth-style alert that no CL is connected: 
```
WARN [07-21|06:21:59.848] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
```
Reason: many repeatative user's questions - "i stuck at block 18999999. what to do?" - with usual answer: `--internalcl`

**Comment by Giulio2002** [comment]
i think this can be closed if caplin is default. if user goes out of their way to use `--externalcl`, they must know what that is
