### ISSUE TITLE
`--prune.mode=minimal` investigate why `amoy` node didn't have `transactions.seg` files

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11271]
`amoy` doesn't have any e3 state files (too small) but logic of prune think that it doesn't need to download most of txs.seg files - and download only 1 latest:
```
 ls /erigon-data/amoy3_remove/snapshots/*tr*
/erigon-data/amoy3_remove/snapshots/v1-009500-009600-transactions-to-block.idx
/erigon-data/amoy3_remove/snapshots/v1-009500-009600-transactions.idx
/erigon-data/amoy3_remove/snapshots/v1-009500-009600-transactions.seg
/erigon-data/amoy3_remove/snapshots/v1-009500-009600-transactions.seg.torrent
```

I did try to hack-fix it by: https://github.com/erigontech/erigon/pull/11267  - but probably it's unrelated

------
another thing - from logs i didn't understand that node is pruned:
```
[INFO] [07-22|06:32:21.906] [snapshots:missed-idx:reopen] Stat       blocks=9600k indices=9600k alloc=855.6MB sys=6.8GB
``` 
probably we must improve this logs somehow too.

**Comment by Giulio2002** [comment]
--prune.mode=minimal does not download blocks for ranges that are already in domains, this is expected behaviour

**Comment by Giulio2002** [comment]
Oh, just read it again, i see...

**Comment by AskAlexSharov** [comment]
maybe also this code breaks at `--prune.mode=minimal`

```
if cfg.blockReader.BorSnapshots().SegmentsMin() == 0 {
    snapTime = snapTime + time.Since(snapStart)
    // SegmentsMin is only set if running as an uploader process (check SnapshotsCfg.snapshotUploader and
    // UploadLocationFlag) when we remove snapshots based on FrozenBlockLimit and number of uploaded snapshots
```
uploader - it's something added by Mark - not sure he using it or not.
