### ISSUE TITLE
Sampled .idx

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11284]
Study how .idx works. It has `map of key to [0;N) interval` and `list of offsets - in EliasFano encoding`. "list of offsets" is big - I think it's possible to make it smaller. Here is an idea:

- Try re-create some existing .idx - and store there `recordNum%2` instead of `recordNum`. Means - index will return to App 2 params: `base offset` and `amount of skips`: App will do `Reset(offset)+Next()` or `Reset(offset)+Skip()+Next()`.

**Comment by Giulio2002** [comment]
Only 20% of `.idx` and `.ef` is for ordinal lookups so this is deemed as not worth it

**Comment by Giulio2002** [comment]
I think I am reopening because it might have some benefit
