### ISSUE TITLE
Tune .bt at bor-mainnet Level0 storage.kv

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11303]
- How big is .bt leaf at bor-mainnet Level0 storage.kv
- How much places in file it touches 
- What if we increase/reduce M

**Comment by awskii** [comment]
increasing M 256-> 1024 lead to ramp of RAM from 106G to 129G on start on mainnet, so for bor effect will be even more dramatic.

bt leafs are not kept in memory, it's just key ordinal (di) and offset (offt) in file for that ordinal kept as elias-fano. Bt node is 16+len(key) bytes (so storage .bt requires more ram)

**Comment by awskii** [comment]
<img width="804" alt="image" src="https://github.com/user-attachments/assets/fe9815c3-9166-41e0-b577-984aa6de4736">
db write timings after start of optimised version at 19 pm are basically flat (<20ms)
