### ISSUE TITLE
Caplin Holesky Snapshots

### ISSUE THREAD

**Issue by Giulio2002** [erigontech/erigon#11311]
Update holesky machine (snapshot producer) and add on the flags `--caplin.archive` `--caplin.backfilling.blob`. also set the automation to publish `blobsidecars` and `beaconblocks` snapshots

**Comment by michelemodolo** [comment]
1) updated to `commit a85b9093f8e79ceb1d3efbd6ffa93379f55577cd` (24 July)
2) fulfilled your request
