### ISSUE TITLE
method handler crashes - `eth_getLogs` - Gnosis Chain

### ISSUE THREAD

**Issue by eth2353** [erigontech/erigon#11336]
#### System information

Erigon version: [v3.0.0-alpha1](https://github.com/erigontech/erigon/releases/tag/v3.0.0-alpha1)

OS & Version: Linux

Commit hash:  6df3f87 (official alpha1 Docker image)

Erigon Command (with flags/config):
```
    command:
      - "--chain=gnosis"
      - "--datadir=/data"
      - "--prune.mode=full"
      - "--port=30305"
      - "--http"
      - "--http.addr=execution"
      - "--http.port=8545"
      - "--http.vhosts=*"
      - "--ws"
      - "--ws.port=8546"
      - "--authrpc.addr=execution"
      - "--authrpc.port=8551"
      - "--authrpc.vhosts=*"
      - "--authrpc.jwtsecret=/jwt_secret"
      - "--externalcl"
```

Consensus Layer: Lodestar v1.20.2

Consensus Layer Command (with flags/config):

```
    command:
      - "beacon"
      - "--network=gnosis"
      - "--checkpointSyncUrl=https://checkpoint.gnosischain.com"
      - "--dataDir=/data"
      - "--execution.urls=http://execution:8551"
      - "--jwt-secret=/jwt_secret"
```

Chain/Network: Gnosis Chain

#### Expected behaviour

External CL is able to retrieve logs from Erigon.

#### Actual behaviour

get_Logs method handler seems to be crashing.

#### Steps to reproduce the behaviour

I just freshly synced this node using the command above, nothing special. The errors in the logs appear when the external CL is on. I was running a pre-alpha version before this ( ced9f000d2ba4b668e07c7c8f282afae773f9b94 ) and I don't remember seeing these errors there.

#### Example log entry

````
[EROR] [07-26|09:23:18.279] RPC method eth_getLogs crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:223 panic.go:770 panic.go:261 signal_unix.go:881 eth_receipts.go:134 value.go:596 value.go:380 service.go:228 handler.go:536 handler.go:486 handler.go:425 handler.go:245 handler.go:338 asm_amd64.s:1695]
[WARN] [07-26|09:23:18.279] [rpc] served                             conn=172.19.0.2:43082 method=eth_getLogs reqid=768 t=3.503925ms err="method handler crashed"
````

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/erigontech/erigon/pull/11337
