### ISSUE TITLE
optimise GetTransactionByHash and GetRawTransactionByHash

### ISSUE THREAD

**Issue by sudeepdino008** [erigontech/erigon#11347]
Sudeep: 
> question about the RPC endpoints: GetTransactionByHash and GetRawTransactionByHash  (in eth_txs.go)
> both use BlockReader#TxnLookup which basically goes through different segments/indexes and return txnRlp and block number.
> then txnRlp is ignored and block number is sent to eth_txs.go (where GetTx and GetRawTx is implemented). Then it fetches block and iterates through the tx and returns that tx.
> 
> wouldn't it be better just to use the txnRlp, rather than ignoring it? We can also ignore figuring out block number for this query. Is there a problem with removing the 2nd step above?

Alex Sharov GMT+7: 

> Probably you right.

**Comment by AskAlexSharov** [comment]
same code exists in `func (api *APIImpl) GetTransactionReceipt`:
```
block, err := api.blockByNumberWithSenders(ctx, tx, blockNum)
	if err != nil {
		return nil, err
	}
	if block == nil {
		return nil, nil // not error, see https://github.com/erigontech/erigon/issues/1645
	}

	var txnIndex uint64
	var txn types.Transaction
	for idx, transaction := range block.Transactions() {
		if transaction.Hash() == txnHash {
			txn = transaction
			txnIndex = uint64(idx)
			break
		}
	}
```
