### ISSUE TITLE
Incorrect prestate balance for Blob-commit transactions

### ISSUE THREAD

**Issue by Otto-AA** [erigontech/erigon#11368]
#### System information

Erigon version: `cast client -r https://eth-pokt.nodies.app/` -> erigon/2.59.3/linux-amd64/go1.21.5

Chain/Network: Ethereum / main

#### Expected behaviour

It should output the correct prestate balance for Blob-Commit transactions.

#### Actual behaviour

It outputs a prestate balance that is `0x20000` too low.

#### Steps to reproduce the behaviour

I've tested it with following command, though it probably affects all types of prestate tracing:

```bash
cast rpc debug_traceBlockByNumber 0x12f94ce '{"tracer": "prestateTracer", "tracerConfig": { "diffMode": true } }'
```

Then inspect the prestate balances for following commits:

- [0xcab65b826c4ad4a92b0f35a567f9f8e12930b02726b31a2f05e3c1a9ffda25b7](https://etherscan.io/tx/0xcab65b826c4ad4a92b0f35a567f9f8e12930b02726b31a2f05e3c1a9ffda25b7/advanced#statechange)
- [0x51e9dab90955d3cfb662a32cefb0d49d1755712ba0cdc0fcf6cbac1d224c1da3](https://etherscan.io/tx/0x51e9dab90955d3cfb662a32cefb0d49d1755712ba0cdc0fcf6cbac1d224c1da3#statechange)

**Comment by somnathb1** [comment]
Will take it up soon
