### ISSUE TITLE
Missing docker image v2.60.5

### ISSUE THREAD

**Issue by jmcruz1983** [erigontech/erigon#11391]
Seems the build system mixed up some image tags in [docker hub](https://hub.docker.com/r/thorax/erigon/tags),
as before we had **v2.60.4** but now new **2.60.5** is published without the **v** suffix

Also 3.X version is published without **v** suffix

Can we align the image tags?
Thanks

**Comment by lystopad** [comment]
Hello @jmcruz1983 .
Thank you for the issue.
We apologize for this inconvenience.

We are aware of the problem with publishing the images and version tags.
We have been working on modernizing our automation in recent weeks. In the coming releases we hope to publish docker imageries for multiple architectures. These will be published in a different docker repository.

Please keep an eye on the release notes.

Best regards
@lystopad

**Comment by jmcruz1983** [comment]
Thanks @lystopad 
Can you provide the new docker repository?

**Comment by yperbasis** [comment]
Fixed for [v2.60.6](https://github.com/erigontech/erigon/releases/tag/v2.60.6)
