### ISSUE TITLE
Prune `kv.HeaderCanonical` table

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11413]
Reason: to reduce `chaindata` size 

Note:
Probably it's very complex task (this tables are used everywhere) - and can be done by many PR's
Also maybe `HeadersTotalDifficulty` and `MaxTxNum` is much more low-hanging fruit to reduce Chaindata size

Now: we store all `kv.HeaderCanonical` and `kv.HeaderNumber` - never delete

Can:
- enable headers.idx ReduceFalsePositives feature by default
- prune old `kv.HeaderCanonical`/`kv.HeaderNumber` from DB
- likely it will make `IsCanonical` request - more expensive for old blocks. Need investigate/measure. 

```
BorMainnet: 
go run ./cmd/diag dbs  | grep -v 0B | grep GB
| CanonicalHeader             |   59988237 | 2.8GB  |
| HeaderNumber                |   59986000 | 4.7GB  |
| HeadersTotalDifficulty      |   59988237 | 3.2GB  |
| MaxTxNum                    |   59986000 | 1.5GB  |
```

Also can make decision to keep it as-is for simplicity/stability

**Comment by Giulio2002** [comment]
I am working on it, i will also prune HeaderNumber table - https://github.com/erigontech/erigon/pull/11634
