### ISSUE TITLE
No Docker image "thorax/erigon:v2.60.5" on Docker Hub

### ISSUE THREAD

**Issue by daverolo** [erigontech/erigon#11425]
Docker Hub -> https://hub.docker.com/r/thorax/erigon/tags

Until v2.60.4 you always had Docker images like this:
- **docker pull thorax/erigon:v2.60.4**
- docker pull thorax/erigon:2.60.4-arm64
- docker pull thorax/erigon:2.60.4-amd64

Since v2.60.5 the the sole "v2.60.5" image is missing and only these are there:
- docker pull thorax/erigon:2.60.5-arm64
- docker pull thorax/erigon:2.60.5-amd64

Which implies that **_docker pull thorax/erigon:v2.60.5_ is missing**.

Is this a issue in the build pipeline or the new default?

**Comment by lystopad** [comment]
Hello @daverolo !
Thank you for the issue.

We are aware of the problem with publishing the images.
We have been working on modernizing our automation in recent weeks. In the coming releases we hope to publish docker imageries for multiple architectures. These will be published in a different docker repository.
We apologize for this inconvenience.

Please keep an eye on the release notes.

Best regards
@lystopad

**Comment by zekchan** [comment]
@lystopad so is [2.60.5-amd64](https://hub.docker.com/layers/thorax/erigon/2.60.5-amd64/images/sha256-199f46cb03573a6d1d0b296a73c252d2950a6d8eba8cf0526f0fc283d23be1a3?context=explore) tag is fine? It is 30 mb instead of 400mb previouses

**Comment by lystopad** [comment]
@zekchan this image contains only "erigon" binary without other our binaries, like "evm", "rpcdaemon", "observer" etc.
We are working on new Docker images and automation. Hopefully it will be available soon.

Best regards
@lystopad

**Comment by samcm** [comment]
@lystopad are those extra binaries still not available within the main Erigon images..?

```bash
 docker run --rm -it --entrypoint /bin/sh erigontech/erigon:2.61

$ ls /usr/local/bin
erigon
```
