### ISSUE TITLE
Erigon Dev Chain Startup bug using Custom Genesis

### ISSUE THREAD

**Issue by dhyaniarun1993** [erigontech/erigon#11462]
#### System information

Erigon version: `erigon version 3.00.0-alpha1-3ba599de`

OS & Version: OSX

Commit hash: 3ba599d

Erigon Command (with flags/config): 
```
./build/bin/erigon --datadir /tmp/erigon-data init genesis.json
./build/bin/erigon --datadir /tmp/erigon-data --http=true --http.port=8555 --http.api=eth,erigon,web3,net,debug,trace,txpool,parity --port=30313 --chain=dev --nat=none --externalcl --networkid=1515 --authrpc.port=9555
```

Consensus Layer: externalcl

Chain/Network: Dev

#### Expected behaviour
Erigon should be able to start

#### Actual behaviour
Erigon is returning the error
```
EROR[08-02|18:24:48.866] [7/9 Execution] Wrong trie root of block 0: 6a0673c691edfa4c4528323986bb43c579316f436ff6f8b4ac70854bbd95340b, expected (from header): ee84de5f1bdc3a5ced31c70bad61378f470dd5bf6afddc33f31eb618463e1a1f. Block hash: c5902001cfab2bfb6cbfb5e752ab11be44af47d50dbd777a02f7098c169e780b 
EROR[08-02|18:24:48.873] [7/9 Execution] Wrong trie root of block 0: 6a0673c691edfa4c4528323986bb43c579316f436ff6f8b4ac70854bbd95340b, expected (from header): ee84de5f1bdc3a5ced31c70bad61378f470dd5bf6afddc33f31eb618463e1a1f. Block hash: c5902001cfab2bfb6cbfb5e752ab11be44af47d50dbd777a02f7098c169e780b 
```

#### Steps to reproduce the behaviour
Run the command provided above with the genesis file attached.

Logs and Genesis files attached
[erigon.log](https://github.com/user-attachments/files/16470726/erigon.log)
[genesis.json](https://github.com/user-attachments/files/16470727/genesis.json)
[init.log](https://github.com/user-attachments/files/16470728/init.log)

**Comment by JkLondon** [comment]
I think it's because in e3 we don't take your custom genesis when starting the client (in init all was ok)
This PR https://github.com/erigontech/erigon/pull/11550 with flag --custom.genesis.file=genesis.json probably should fix it. (As I've tested on my own machine)
