### ISSUE TITLE
restore `DISCARD_HISTORY` feature or replace it by `--prune.mode=full`

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11481]
- to not produce .v/.ef files (`--prune.mode=full` can do it)
- to skip all history writes to db (even to ETL)
- make sure node still can produce .kv files and prune domains data
(use `integration stage_exec`)

**Comment by Giulio2002** [comment]
We already do it although it is a little bit hacky, we DiscardInvertedIndexes if anything except for deposit contract related stuff
