### ISSUE TITLE
`eth_syncing` support at bor chains 

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11487]
reason: `rawdb.ReadLastNewBlockSeen` not set at bor chains. 
need to implement https://github.com/erigontech/erigon/pull/10398 for bor-mainnet and amoy (probably in `StageLoop`)

**Comment by taratorio** [comment]
this will be supported automatically when we switch to Astrid standalone (scheduled for alpha6 or alpha7 after alpha5 is released)

**Comment by AskAlexSharov** [comment]
seems implemented in https://github.com/erigontech/interfaces/pull/245
