### ISSUE TITLE
Potential unexpected change in holiman uint256 String() function that may affect Erigon's functionality

### ISSUE THREAD

**Issue by indanielo** [erigontech/erigon#11503]
I have detected that the function in a library, specifically the holiman uint256 library, has changed its implementation for the String() method. In version v1.2.3, which was used by Erigon v2.59.0, the implementation was: https://github.com/holiman/uint256/blob/v1.2.4/conversion.go#L648, while in version v1.2.4, which is currently used by Erigon, for example, in version v2.60.5, the implementation is: https://github.com/holiman/uint256/blob/v1.2.3/conversion.go#L634.

This means that in v2.59.0, when this version was used in Erigon, a hexadecimal value was expected, and indeed, that’s what the function returned, while now it’s returning a decimal. Could this not cause issues in the functioning of Erigon? I’ve noticed that this function is used in several places, and it seems like a significant change (and not just a patch).

**Comment by AskAlexSharov** [comment]
i reviewed and seems we not use it widely. 
anyway - even if it breaks - it breaks for better compatibility with `big.Int` which we used before `uint256`

**Comment by AskAlexSharov** [comment]
thank you for rising it
