### ISSUE TITLE
Optimize `TxNum` index

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11519]
It's 2Gb in bor-mainnet. And it's 99% immutable
So, let's optimize it - by encoding all old values as EliasFano - immutable - write once in `FillDBFromSnapshots()` and never update
Let's on this step store it in DB (later maybe we will move it to mmap file)

Optimize `rawdbv3.TxNums.FindBlockNum`: 
- first need make decision - search in immutable or mutable parts
- then binary search only in 1 part

**Comment by Giulio2002** [comment]
Oh this is also done
