### ISSUE TITLE
How to request for  historical changesets from Erigon Node.

### ISSUE THREAD

**Issue by xuht724** [erigontech/erigon#11574]
I know that the erigon db will store historical account changedSet, I would like to ask if there is a rpc allowing us to know which contracts and which storage slots changed in the transaction execution process in the block. I know the `Storage ChangedSets` will store the `prior` value. 

How to access those db via erigon node?

Is it possible to retrieve the `post` value and how?

**Comment by AskAlexSharov** [comment]
1. Can call —private.api.addr https://github.com/erigontech/interfaces 
2. Can read db directly: db supports it. Just don’t open too long read transactions  (>10min) to prevent db grow

**Comment by xuht724** [comment]
> @xuht724 Search in .proto - there is OnBlock subscription. there are state changes of new blocks.

I meet some problem in using `erigon/interfaces` and propose [an issue](https://github.com/erigontech/interfaces/issues/226). Besides, I do not find the onBlock subscription. It is pity that there is no docs to tell use how to send grpc to erigon node. It is a little difficult for us.
