### ISSUE TITLE
add missing tests of kurtosis assertoor ci

### ISSUE THREAD

**Issue by sudeepdino008** [erigontech/erigon#11590]
current active tests - https://github.com/erigontech/erigon/pull/11464/files#diff-b45e49409c33f39133315225d30c02d8cfacfd9a53d1157bca61284683a4c498R22

**Comment by sudeepdino008** [comment]
kurtosis assertoor ci added here - https://github.com/erigontech/erigon/issues/10943

**Comment by yperbasis** [comment]
Actually, I'd say passing EL tests is high priority and passing CL should also be high priority closer to the GA release of E3/Caplin.

**Comment by yperbasis** [comment]
More immediately, let's try to fix `block-proposal-check`

**Comment by sudeepdino008** [comment]
https://github.com/erigontech/erigon/pull/11641

**Comment by sudeepdino008** [comment]
kurtosis runs are happening - https://github.com/erigontech/erigon/actions/workflows/test-kurtosis-assertoor.yml
