### ISSUE TITLE
receipts generator: allow fast-path by checking cache

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11603]
RPC now: 
```
beginRo
genAndCheckCache
```
need change to:
```
checkCache
beginRo
genAndSaveToCache
```
In-short: don't open rotx if possible

P2P now: 
```
limiter.Get(1)
genAndCheckCache
```
need change to:
```
checkCache
limiter.Get(1)
genAndSaveToCache
```
In-short: don't wait for limiter free slot - if can get data from cache. We limiting execution.

**Comment by JkLondon** [comment]
done by #12050
