### ISSUE TITLE
Caplin CPU

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11638]
I noticed bormainnet on chain-tip using 33% of cpu, and ethmainnet using 99% of cpu (1 core). 
Here is the pprof of 1minute from chain-tip - much of bls verify - don't know is it good or not:

[mainnet-chain-tip.pdf](https://github.com/user-attachments/files/16631889/mainnet-chain-tip.pdf)

And ethmainnet using 2x more goroutines (using flag `--no-downloader`)
<img width="1578" alt="Screenshot_2024-08-14_at_13 43 45" src="https://github.com/user-attachments/assets/ef9f7afe-fc8e-458d-8ed7-6a4c2c1b036e">

**Comment by Giulio2002** [comment]
Yes, ok got more concrete data. We probably need to implement the connection gater for incoming network: https://docs.libp2p.io/concepts/security/dos-mitigation/

**Comment by Giulio2002** [comment]
<img width="1523" alt="Screenshot 2024-08-17 alle 17 36 29" src="https://github.com/user-attachments/assets/84f86f4b-86b0-44f6-a1cb-02da33bceead">

Like 90% of the goroutines is just libp2p

**Comment by Giulio2002** [comment]
I see a bunch of ways to make goroutines better:

* Use `ResourceManager` and limit StreamInBound/StreamOutBound
* Use workers instead of spawning a gouritne each time for `listenforPeers`
