### ISSUE TITLE
erigon3 --download-verify=true stucks indef. at progress=0.00%

### ISSUE THREAD

**Issue by SLoeuillet** [erigontech/erigon#11670]
#### System information

Erigon version: v3.0.0-alpha2-94-g12ebd14c56

OS & Version: Ubuntu 24.04 amd64

Commit hash: 12ebd14c562cdef777ba106fc218594ffdc37e0d

Erigon Command (with flags/config):

--download.verify=true

Chain/Network: bor-mainnet

#### Expected behaviour

It verifies all already downloaded files (1449/1479) then goes to next stage (downloading remaining 30 files)

#### Actual behaviour

Aug 19 07:14:49 polygon01-mainnet-ovh erigon[498115]: [INFO] [08-19|07:14:49.459] [snapshots] Verify                       progress=0.00% files=0/1449 sz_gb=0

until the end of times

#### Steps to reproduce the behaviour

Add --download.verify=true

#### Backtrace

````
[backtrace]
````

**Comment by SLoeuillet** [comment]
Same with git_tag=v3.0.0-alpha2-96-ge4eb9fcc2c (e4eb9fcc2c)

**Comment by dvovk** [comment]
Should be fixed with #11874
