### ISSUE TITLE
Diagnostics failed to parse data related to CPU info

### ISSUE THREAD

**Issue by taratorio** [erigontech/erigon#11674]
Reported by a user on discord: https://discord.com/channels/687972960811745322/738982866670714901/1273991868073508894

#### System information

Erigon version: `2.60.6-d4647a13`

OS & Version: Ubuntu 24.04 LTS amd64

Erigon Command (with flags/config): N/A

Consensus Layer: N/A

Consensus Layer Command (with flags/config): N/A

Chain/Network:  N/A

#### Expected behaviour
Parse cpu info

#### Actual behaviour
```
[Diagnostics] Failed to parse data       data="{"cores":1,"modelName":"Intel(R) Xeon(R) E-2388G CPU @ 3.20GHz","mhz":5100}" type=*[]diagnostics.CPUInfo
```

#### Steps to reproduce the behaviour
Start Erigon on Linux

**Comment by SLoeuillet** [comment]
Had that with at least 2 versions on 2 different nodes

Aug 14 08:04:43 polygon50-mainnet-ovh erigon[405078]: [INFO] [08-14|08:04:43.253] Build info                               git_branch=release/2.60 git_tag=v2.60.5-19-g60971ea2f8 git_commit=60971ea2f825b68230fceb35ebde8c02b26c061e
Aug 14 08:05:10 polygon50-mainnet-ovh erigon[405078]: [WARN] [08-14|08:05:10.478] [Diagnostics] Failed to parse data       data="{\"cores\":1,\"modelName\":\"Intel(R) Xeon(R) E-2388G CPU @ 3.20GHz\",\"mhz\":5100}" type=*[]diagnostics.CPUInfo

Aug 14 14:45:27 polygon01-mainnet-ovh erigon[432704]: [INFO] [08-14|14:45:27.483] Build info                               git_branch=main git_tag=v3.0.0-alpha2-68-ga264b9f867 git_commit=a264b9f86752695fa5e0a0f89e53f03ceeab6185
Aug 14 14:45:54 polygon01-mainnet-ovh erigon[432704]: [WARN] [08-14|14:45:54.140] [Diagnostics] Failed to parse data       data="{\"cores\":1,\"modelName\":\"Intel(R) Xeon(R) E-2388G CPU @ 3.20GHz\",\"mhz\":5100}" type=*[]diagnostics.CPUInfo

**Comment by dvovk** [comment]
The issue was triggered by a data structure update and may occur only once when a new object is written to the database. It does not impact the functionality of the node.
