### ISSUE TITLE
Caplin: `HasBlock` call becomes red on heap profiling

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11704]
[mainnet.pdf](https://github.com/user-attachments/files/16688065/mainnet.pdf)

**Comment by Giulio2002** [comment]
i see - it should be easily fixable tbh

**Comment by Giulio2002** [comment]
i mean - it is not really significant because this is still 80% I/O and network, but i can make it better

**Comment by Giulio2002** [comment]
<img width="677" alt="Screenshot 2024-08-23 alle 23 28 39" src="https://github.com/user-attachments/assets/ae31714c-59c2-4258-946b-0979308d064e">
There you go, see - i just fixed it and now `FrozenBlocks` is the bottleneck lol.

**Comment by Giulio2002** [comment]
<img width="407" alt="Screenshot 2024-08-23 alle 23 53 26" src="https://github.com/user-attachments/assets/9f85fadd-283b-4e04-9853-2f05d2c25f77">

Removed frozenblocks too with some generic optimizations, startup time got better and now it seems to be mostly only I/O
