### ISSUE TITLE
Fix all Hive tests and include them into CI

### ISSUE THREAD

**Issue by yperbasis** [erigontech/erigon#11716]
- [x] Add hive tests on Push - PR pending https://github.com/erigontech/erigon/pull/12238
- [x] Fix hive tests not starting
- [ ] Add hive to Makefile

**Comment by somnathb1** [comment]
Many of the issues at the tip of `main` branch are related to latest PRs on Erigon-3. It so happens that there are design changes happening all the time. The main focus of this issue would be to integrate the CI to automate the process of indicating which PR broke which hive test(s). 
The next focus would be to include some fixes applied for some fixes. Further fixes for one or more hive tests is too big for a scope of a single issue.

**Comment by AskAlexSharov** [comment]
`Further fixes for one or more hive tests is too big for a scope of a single issue.` - use it as an umbrella-issue: with many check-boxes/links_to_other_issues
