### ISSUE TITLE
How does Erigon locate the historical state for transaction simulation?

### ISSUE THREAD

**Issue by xuht724** [erigontech/erigon#11800]
I'm trying to understand how Erigon locates the state used in simulating transactions based on historical state data.
To illustrate, I'm using the following example where I call the getReserves function on a UniswapV2 pool at a specific block number.

```typescript
import { uniV2PoolABI } from "src/abi";
import { createPublicClient, getContract, http } from "viem";

const uniswapv2_usdc_usdt = '0x3041CbD36888bECc7bbCBc0045E3B1f144466f5f';

const client = createPublicClient({
    transport: http(process.env.HTTP_NODE_URL)
})

let contract = getContract({
    abi: uniV2PoolABI,
    address: uniswapv2_usdc_usdt,
    client: client
})

async function main(){
    let begin = performance.now()

    let reserve = await contract.read.getReserves({
        blockNumber: 20638283n
    });

    let end = performance.now()
    console.log('end - begin', end - begin, 'ms');
    console.log(reserve);
}
main();
```

## Context:
- Block Number: 20638283
- Last Transaction That Changed Pool Balance: Block Number 20637881

## Question:
For go-ethereum, we will create a stateDB object using the `stateRoot` of block 20638283, resolve the state Trie and storage Trie to given the account address and storage slot. 

I know erigon will store the `accountStorageHistory` in the db but I would like to ask how erigon locate the state last change. More specifically, how erigon implement the algorithm to retrieve the storage slot changed in 20637881 in above example.

The source code of erigon is hard to understand and there is no related explanation in the internet. Therefore, I propose such issue here and hope to get answers.

**Comment by AskAlexSharov** [comment]
1. if need re-exec historical block with tracer - see implementation of any historical blocks execution RPC: `debug_traceBlockByNumber` `PrivateDebugAPIImpl.TraceBlockByNumber`
2. if need read range of historical state - see implementation of `debug_accountAt` `PrivateDebugAPIImpl.AccountAt`, `debug_storageRangeAt` `PrivateDebugAPIImpl.StorageRangeAt`

**Comment by xuht724** [comment]
> 1. if need re-exec historical block with tracer - see implementation of any historical blocks execution RPC: `debug_traceBlockByNumber` `PrivateDebugAPIImpl.TraceBlockByNumber`
> 2. if need read range of historical state - see implementation of `debug_accountAt` `PrivateDebugAPIImpl.AccountAt`, `debug_storageRangeAt` `PrivateDebugAPIImpl.StorageRangeAt`

Thanks for your info. I am reading the implementation of these code and I have something confusing:
Here is the implementation of getStorageRangeAt. It seems r is an iterator that we could get desired state given contract.
but I want to ask , how could we know the state last changed, where to store this information. Sorry that I could fully understand the process.

```go
	r, err := ttx.DomainRange(kv.StorageDomain, fromKey, toKey, txNum, order.Asc, maxResult+1)
	if err != nil {
		return StorageRangeResult{}, err
	}
	defer r.Close()
	for i := 0; i < maxResult && r.HasNext(); i++ {
		k, v, err := r.Next()
		if err != nil {
			return StorageRangeResult{}, err
		}
		if len(v) == 0 {
			continue // Skip deleted entries
		}
		key := libcommon.BytesToHash(k[20:])
		seckey, err := libcommon.HashData(k[20:])
		if err != nil {
			return StorageRangeResult{}, err
		}
		var value uint256.Int
		value.SetBytes(v)
		result.Storage[seckey] = StorageEntry{Key: &key, Value: value.Bytes32()}
	}
```

**Comment by AskAlexSharov** [comment]
`how could we know the state last changed` - what?
`so how erigon know the changed value after the transaction when getting state` - just pass `txNum+1` as a parameter. In theory: or can find value in history (changeSets) or in latest state (PlainState/Domain). In Erigon2 it's `historyv2read.GetAsOf` in Erigon3 it's `DomainRoTx.GetAsOf`.

**Comment by AskAlexSharov** [comment]
Short story on "what happening if store in history values `AFTER` change": https://blog.ethereum.org/2023/09/12/geth-v1-13-0 (in short: pruning becomes impossible).

**Comment by Giulio2002** [comment]
Hey, please ask these kind of questions and not on Github, this is for issues with Erigon not for Q&A.
