### ISSUE TITLE
E3: polygon mainnet wrong trie root 

### ISSUE THREAD

**Issue by Abbrske** [erigontech/erigon#11835]
#### System information

Erigon version: 3.00.0-alpha2

OS & Version: Linux

Commit hash: 7b1e16cbf5f0309c9be227c392b86e8abeaacb39

Erigon Command (with flags/config):
erigon --datadir="${datadir}"  --chain bor-mainnet --db.pagesize "4KB" --db.size.limit "4TB" \
--sync.loop.block.limit 500_000 --batchSize "10g" \
--externalcl --bor.heimdall="http://127.0.0.1:1317" --bor.milestone \
--authrpc.port 8551 --private.api.addr "localhost:9091" \
--diagnostics.disabled  --txpool.disable

Consensus Layer: heimdalld 1.0.7

Chain/Network:  bor-mainnet

#### Actual behaviour
[EROR] [09-03|04:29:35.873] [7/9 Execution] Wrong trie root of block 61350096: 99a2e56b676988ae78abae8c7ca7ab502f0ead5e8f9af5186ecab26b0e34c58c, expected (from header): 967d9594845dd14f371      da6d6547a7af45332dd265787602f323e466f564c0227. Block hash: 11337e5bd5a8677a988ebb243d20917570bcaa19831853decf819ae6643b2473
[EROR] [09-03|04:29:35.893] Staged Sync                              err="bad block unwinding"

#### Steps to reproduce the behaviour
When it happened, I did rm chaindata -rf and sync again. The stuck block got passed. but after more then 20 hours runing, this problem happened again. This problem happens almost every day.

I also run a node for the eth mainnet with the same erigon exe and config. But this problem only occurs in polygon.

**Comment by Giulio2002** [comment]
Hi, we fixes this in alpha3, however this requires a full resync

**Comment by Abbrske** [comment]
@Giulio2002 
Thank you! 

Can I use snaphots download for alpha3 full resync?
Do I need to redownload the domain snapshot? I saw the old domain file in https://github.com/erigontech/erigon-snapshot bor-mainnet.toml not been changed.
Is The block snapshot is compatible？Can I only download the domain snapshot to save time?

**Comment by AskAlexSharov** [comment]
`alpha3` require full re-sync
