### ISSUE TITLE
silkworm in release builds

### ISSUE THREAD

**Issue by battlmonstr** [erigontech/erigon#11846]
Currently release builds (e.g. [erigon_2.60.6_linux_amd64.tar.gz](https://github.com/erigontech/erigon/releases/download/v2.60.6/erigon_2.60.6_linux_amd64.tar.gz)) and docker images are built without silkworm support using "nosilkworm" build tag. Some of them have only the "erigon" binary included.

We'd like to support silkworm integration in Linux amd64 builds and docker images.
Optionally macOS arm64 builds could have it.

#### Implementation details
* In order to run erigon with silkworm a silkworm dynamic library `libsilkworm_capi.so` is needed. [silkworm_lib_path.sh](https://github.com/erigontech/erigon/blob/main/turbo/silkworm/silkworm_lib_path.sh) script can print a path to that file.
* `libsilkworm_capi.so` depends on glibc, so the docker image for running it must not be based on Alpine.
* Currently silkworm is not supported for Linux arm64, and supporting it requires a lot of effort. This can be discussed.
* silkworm binary is not supported on macOS amd64 due to CI limitations (macOS amd64 is a deprecated platform). 
* silkworm is not supported for Windows, and there's no plan for it.

**Comment by lystopad** [comment]
Done for release/2.60:
https://github.com/erigontech/erigon/pull/12331
