### ISSUE TITLE
Erigon `2.60.4` returns "error":"Reverted" for transaction that is valid

### ISSUE THREAD

**Issue by jwelch-qn** [erigontech/erigon#11871]
#### System information

Erigon version: `erigon/2.60.4`

OS & Version:  `Ubuntu 22.04.4 LTS`

Commit hash: 72ab70b

Erigon Command (with flags/config): 
```--data '{"jsonrpc":"2.0","method":"trace_filter","id":37,"params":[{"fromBlock":"0x13b86a0","toBlock":"0x13b86a0"}]}'|jq '.result[] | select(.action.from == "0xeff584e8336da7a23ee32ea19a937b016d69d589" and .transactionHash == "0x815e0c2b8d4973bc797fc20ff707ca77f9a44882dad7e229f0bbf61ebeb98e66")'```

Chain/Network: Ethereum Mainnet

#### Expected behaviour
Etherscan shows that it is indeed a executed transaction:
https://etherscan.io/tx/0x815e0c2b8d4973bc797fc20ff707ca77f9a44882dad7e229f0bbf61ebeb98e66

Compared with nethermind:
```"action": {"callType": "call", "from": "0xeff584e8336da7a23ee32ea19a937b016d69d589", "gas": "0x2a778", "input": "0x88676cad0000000000000000000000000000000000000000000000000000000000000001", "to":"0xa6f93249580ec3f08016cd3d4154aadd70ac3c96", "value": "0x0"}, "blockHash": "0x57ae03732ad0e360a6e7a84e227dd260beb9d77b6a798b17fa519e63b9041cfe", "blockNumber": 20678304, "result":{"gasUsed": "0x1a0d9", "output": "0x"}, "subtraces": 2, "traceAddress": [], "transactionHash": "0x815e0c2b8d4973bc797fc20ff707ca77f9a44882dad7e229f0bbf61ebeb98e66", "transactionPosition": 76, "type": "call"}   ```

#### Actual behaviour
```{
  "action": {
    "from": "0xeff584e8336da7a23ee32ea19a937b016d69d589",
    "callType": "call",
    "gas": "0x2a778",
    "input": "0x88676cad0000000000000000000000000000000000000000000000000000000000000001",
    "to": "0xa6f93249580ec3f08016cd3d4154aadd70ac3c96",
    "value": "0x0"
  },
  "blockHash": "0x57ae03732ad0e360a6e7a84e227dd260beb9d77b6a798b17fa519e63b9041cfe",
  "blockNumber": 20678304,
  "error": "Reverted",
  "result": {
    "gasUsed": "0x8bb8",
    "output": "0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000038456967656e506f642e676574506172656e74426c6f636b526f6f743a20696e76616c696420626c6f636b20726f6f742072657475726e65640000000000000000"
  },
  "subtraces": 2,
  "traceAddress": [],
  "transactionHash": "0x815e0c2b8d4973bc797fc20ff707ca77f9a44882dad7e229f0bbf61ebeb98e66",
  "transactionPosition": 76,
  "type": "call"
}```


#### Steps to reproduce the behaviour
```curl <erigon_node> \
-X POST \
-H "Content-Type: application/json" \
--data '{"jsonrpc":"2.0","method":"trace_filter","id":37,"params":[{"fromBlock":"0x13b86a0","toBlock":"0x13b86a0"}]}'|jq '.result[] | select(.action.from == "0xeff584e8336da7a23ee32ea19a937b016d69d589" and .transactionHash == "0x815e0c2b8d4973bc797fc20ff707ca77f9a44882dad7e229f0bbf61ebeb98e66")'```

**Comment by yperbasis** [comment]
Fixed by PR #12559 and will be released in v2.60.10.
