### ISSUE TITLE
Cannot download docker erigon 2.60.7 on amd64 server from new repo erigontech/erigon

### ISSUE THREAD

**Issue by insider89** [erigontech/erigon#11965]
#### System information

Erigon version: 2.60.7

OS & Version: Linux (k8s)

Chain/Network: 

#### Expected behaviour
Image successfully download

#### Actual behaviour
```
Warning  Failed     47s (x4 over 2m27s)  kubelet            Failed to pull image "docker.io/erigontech/erigon:2.60.7": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/erigontech │
│ /erigon:2.60.7": no match for platform in manifest: not found
```

#### Steps to reproduce the behaviour
Try to download image on server with architecture:
```
uname -m
x86_64
```

I see that new repo has `linux/amd64/v2`, not sure what v2 means, but looks like it's a problem. I can successfully download it from old repo `thorax/erigon`

#### Backtrace

````
[backtrace]
````

**Comment by lystopad** [comment]
@insider89 , hi

v2 means amd64 microarchitecture, see [here](https://en.wikipedia.org/wiki/X86-64) for more details.

We compiled erigon binaries for AMD64 microarchitecture level 2 (see [here](https://go.dev/doc/install/source#environment) ) for more details.

Please, share your docker package version and OS.
Recently similar issue for another user was fixed upgrading to the latest docker package.

For more details: 
- https://docs.docker.com/engine/release-notes/23.0/
`Add support for pulling images with custom amd64 micro-architecture feature levels as supported by the latest versions of Go, GCC, LLVM, and other compiler tools. [moby/moby#43434](https://github.com/moby/moby/pull/43434)`

**Comment by insider89** [comment]
Hey @lystopad ,

```
root@public-nodes-10 ~ # containerd -v
containerd containerd.io 1.6.32 8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
root@public-nodes-10 ~ # cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by lystopad** [comment]
@insider89 , hi

Please, try this image -- erigontech/erigon:main-1eff2f4
It is multi-platform docker image supporting two platforms -- linux/arm64 and linux/amd64.
But binaries for amd64 Architecture was built using GOAMD64=v2.
Let me know how it works in your case.

**Comment by insider89** [comment]
@lystopad I can confirm, that image `erigontech/erigon:main-1eff2f4` started successfully.

**Comment by lystopad** [comment]
Hi @insider89

See my reply https://github.com/erigontech/erigon/issues/11932#issuecomment-2358099795 

Best regards
@lystopad
