### ISSUE TITLE
Automated docker builds for docker_ branches

### ISSUE THREAD

**Issue by yperbasis** [erigontech/erigon#11983]
The old `thorax` dockerhub has a rule that builds images on commits to branches starting from `docker_`:
<img width="1375" alt="Screenshot 2024-09-13 at 10 34 12" src="https://github.com/user-attachments/assets/152b8c72-2aa1-4ee2-909f-6347a04e6a71">

We need to port this feature to the new `erigontech` dockerhub. However, we can do it by relying on GitHub actions (like it's done for `main`) instead of dockerhub rules.

**Comment by lystopad** [comment]
Erigontech docker repository configured to run automatic builds for new commits in branches matching pattern "docker_*".
Docker images will be published (replacing old ones) with tag "docker_{\1}" matching source branch.
