### ISSUE TITLE
debug_traceBlockByNumber missing tx hash 

### ISSUE THREAD

**Issue by ella-quicknode** [erigontech/erigon#11987]
#### System information

Erigon version: `erigon/2.60.1/linux-amd64/go1.22.3`
OS & Version: `Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-112-generic x86_64)`

Chain/Network: Polygon / Matic

#### Actual behaviour

On block number `61724464` , there should be 62 txns, so I tested on `trace_block` and `eth_getBlockByRecipt`, all return total of 62 txns.   When calling `debug_traceBlockByNumber` method, it returned only **61** tx, and missing tx hash is `0xf3f71a4837a36f5eb821236a90344d08b2a9f53632d58e2a8642244864c60ff1` 

#### Steps to reproduce the behaviour

```
curl  -X POST \                             
  'http://localhost:8545' \
  --header 'Content-Type: application/json' \
  --data-raw '{"method":"debug_traceBlockByNumber","params":["0x3add730", {"tracer": "callTracer"}],"id":1,"jsonrpc":"2.0"}' 
```

**Comment by sudeepdino008** [comment]
the missing tx is a state sync call. It might need some extra config and needs a fully synced node to check, I'm checking. Will report once I know more details.

**Comment by ella-quicknode** [comment]
Oh ok, thanks for that. this flag `borTraceEnabled` works.
