### ISSUE TITLE
High CPU usage on e3 sepolia

### ISSUE THREAD

**Issue by wmitsuda** [erigontech/erigon#11994]
Not sure if this is a false positive or a regression, but I didn't notice it before.

Around ~after alpha 3, I've been noticing a constant CPU usage, noticeable both by htop and CPU fans constantly spinning.

Linux machine, debian bookworm.

I'm uploading a 30s pprof output.

[trace.out.gz](https://github.com/user-attachments/files/17000412/trace.out.gz)

**Comment by wmitsuda** [comment]
screenshot snipet, not sure if this is the most representative part, anyway the pprof has the entire raw info

<img width="1667" alt="image" src="https://github.com/user-attachments/assets/4a1114b3-f690-42d2-b5ae-a51d4c19c315">

**Comment by AskAlexSharov** [comment]
try update - Giulio told that he fixed many CPU-things in Caplin recently

**Comment by wmitsuda** [comment]
alright, for the record, I was using commit `6ac7005c40226e8bd28e9c264cff9702646b702f` from 12/09 main.

I'm going to update to last main now and check again later.

**Comment by wmitsuda** [comment]
I didn't see much improvement using yesterday's main.

Attaching pprof
[trace.out.gz](https://github.com/user-attachments/files/17003833/trace.out.gz)

**Comment by wmitsuda** [comment]
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/0bcd63f7-6c58-4ac3-aff7-8134b2e36eaa">

**Comment by wmitsuda** [comment]
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/015de5a8-f4f6-4deb-a2b4-de37fbfd45d0">

**Comment by Giulio2002** [comment]
Well, this is just normal CPU usage for a CL to be completely honest, maybe some improvement can be made, but do not expect a lot from cryptographic verification

**Comment by wmitsuda** [comment]
Ok, yeah, I think my question was more like "is this expected CPU usage for CL" (in which case this could be closed).

Because I didn't notice the CPU fans of my NUC being so noisy until recently, but that may be just an impression.

**Comment by Giulio2002** [comment]
no `main` has a cpu bug, but blob processing makes sense to me. maybe i can tweak it so that it less prominent
