### ISSUE TITLE
Erigon 3.0.0-alpha3 constantly throwing "Sanitizing invalid bor gasprice oracle ignore price app=gasPriceOracle" warning

### ISSUE THREAD

**Issue by Aracki** [erigontech/erigon#12026]
As soon as Ottersync download has been started for Polygon we are getting warnings:

```
Sanitizing invalid bor gasprice oracle ignore price provided=2 updated=30
```

I guess it is not affecting the sync, but juts curious what it means?

**Comment by shohamc1** [comment]
This is related to [PIP-35](https://forum.polygon.technology/t/pip-35-mingas-increase/13856)
