### ISSUE TITLE
Erigon3 didn't shut down gracefully

### ISSUE THREAD

**Issue by michelemodolo** [erigontech/erigon#12049]
Yesterday (19 Sept 2024) an automation tried to shut down erigon (running on gnosis) gracefully and didn't succeed after several attempts so it resorted to shut it down not gracefully. Log excerpt is hereby attached. Erigon was running from main, commit f62360cc9a0c39be2b140cd22ef1629652f57235 (29Aug). After restart, erigon was able to recover successfully. 

That might be a bug (so I used the `bug` label) or erigon was particularly busy with some heavy internal process.
[erigon_gnosis_excerpt.txt](https://github.com/user-attachments/files/17072261/erigon_gnosis_excerpt.txt)

**Comment by AskAlexSharov** [comment]
hi. seems we fixed it. 

also such bugs hard to reproduce - so, it will be very useful if can grab erigon output (at least 200 first lines of crush and 100 lines of logs before crush) - to understand in which state erigon was. 

closing. feel free to re-open if still the case.
