### ISSUE TITLE
Type of `error` field in structlog logger differs from geth, alloy

### ISSUE THREAD

**Issue by einar-polygon** [erigontech/erigon#12085]
#### System information

Commit hash: c293883ec039ebcc9bb7bbe85807cabee828b4bc

#### Expected behaviour

The field `error` should probably be logged as a string to be compatible with [Geth](https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/logger/gen_structlog.go#L33C3-L33C14), [Alloy](https://docs.rs/alloy-rpc-types-trace/latest/alloy_rpc_types_trace/geth/struct.StructLog.html).

#### Actual behaviour

The field `error` is logged as an object containing a string.

#### Steps to reproduce the behaviour

I don't know of a `tx_id` on a public chain, whose logs contains the `error` field, but here is the command I used to confirm this issue:
```bash
curl $RPC \                                                                                        
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"debug_traceTransaction","params":[tx_id, {"disableStack": true, "disableMemory": true, "disableStorage": true} ], "id":1,"jsonrpc":"2.0"}'  | jq | rg "error" -C 16
```

#### Source

https://github.com/erigontech/erigon/blob/c293883ec039ebcc9bb7bbe85807cabee828b4bc/eth/tracers/logger/json_stream.go#L128-L131

#### Suggested fix

```diff
diff --git a/eth/tracers/logger/json_stream.go b/eth/tracers/logger/json_stream.go
index 5b616e81e7..60b8443b65 100644
--- a/eth/tracers/logger/json_stream.go
+++ b/eth/tracers/logger/json_stream.go
@@ -127,9 +127,9 @@ func (l *JsonStreamLogger) CaptureState(pc uint64, op vm.OpCode, gas, cost uint6
        if err != nil {
                l.stream.WriteMore()
                l.stream.WriteObjectField("error")
-               l.stream.WriteObjectStart()
-               l.stream.WriteObjectEnd()
-               //l.stream.WriteString(err.Error())
+               // l.stream.WriteObjectStart()
+               // l.stream.WriteObjectEnd()
+               l.stream.WriteString(err.Error())
        }
        if !l.cfg.DisableStack {
                l.stream.WriteMore()
```

**Comment by AskAlexSharov** [comment]
tnx. pr: https://github.com/erigontech/erigon/pull/12089

**Comment by einar-polygon** [comment]
@AlexeyAkhunov seems to be the original committer of those lines so tagging him.  Perhaps he knows something I don't about why the line was already there, but commented out (`//l.stream.WriteString(err.Error())`).
