### ISSUE TITLE
erigon_3.0.0-alpha3 can't sync

### ISSUE THREAD

**Issue by zhy827827** [erigontech/erigon#12095]
Running erigon_3.0.0-alpha3 for mannet.I check the log is stuck in a block

Logs:

```
Sep 26 02:49:46 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:46.183] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
Sep 26 02:49:46 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:46.185] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
Sep 26 02:49:46 mainnet-polygon-archive-mm-02 erigon[1351718]: [INFO] [09-26|02:49:46.387] [p2p] GoodPeers                          eth68=16 eth67=2
Sep 26 02:49:46 mainnet-polygon-archive-mm-02 erigon[1351718]: [INFO] [09-26|02:49:46.483] [txpool] stat                            pending=0 baseFee=0 queued=13076 alloc=24.9GB sys=38.7GB
Sep 26 02:49:47 mainnet-polygon-archive-mm-02 erigon[1351718]: [INFO] [09-26|02:49:47.232] [mem] memory stats                       Rss=30.5GB Size=0B Pss=30.5GB SharedClean=4.0KB SharedDirty=0B PrivateClean=1.8GB PrivateDirty=28.7GB Referenced=27.1GB Anonymous=28.7GB Swap=0B alloc=21.4GB sys=38.7GB
Sep 26 02:49:47 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:47.605] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
Sep 26 02:49:47 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:47.616] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
Sep 26 02:49:47 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:47.723] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
Sep 26 02:49:49 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:49.218] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
Sep 26 02:49:49 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:49.230] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
Sep 26 02:49:49 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:49.336] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
Sep 26 02:49:49 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:49.490] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
Sep 26 02:49:50 mainnet-polygon-archive-mm-02 erigon[1351718]: [WARN] [09-26|02:49:50.864] [downloader] InsertHeader: Rejected header marked as bad hash=0x7a640f569649fe32308eab60228bb8b2389c290b36d1451d524ebdb92ab8d353 height=62278659
```

**Comment by sshamanov** [comment]
Same here bor-mainnet
unwind does not work, integration complains about pruning flags
After removing chaindata got another error in logs:

```
polygon-erigon  | [EROR] [09-26|20:30:38.242] Staged Sync                              err="[2/9 Headers] [2/9 Headers] parent's total difficulty not found with hash 0968592a7b2ed258307157ce0515fd023c682ea60e948698e7f785133d3abfd0 and height 62010999 for header 5973461d87c54092d25131fd483743ffa0184c2949a8f2eb3517f21e4ba100f6 62011000: <nil>"
```

**Comment by zhy827827** [comment]
erigon_3.0.0-alpha4  doesn't sync the data

`Oct 08 03:39:24 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:24.748] [7/9 Execution] Done                     blk=62436676 blks=1003 blk/s=49.8 txs=49055 tx/s=2.43k gas/s=414.52M buf=42.7MB/2.0GB stepsInDB=0.00 step=2940.0 alloc=24.3GB sys=44.3GB
Oct 08 03:39:24 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [EROR] [10-08|03:39:24.748] Staged Sync                              err="[7/9 Execution] StateV3.Apply: hash sort failed: loadIntoTable : unfold: Branch failed: storage file not found"
Oct 08 03:39:25 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:25.301] [7/9 Execution] starting                 from=62435674 to=62446291 fromTxNum=4593769858 offsetFromBlockBeginning=0 initialCycle=true useExternalTx=false
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:45.309] [7/9 Execution]                          blk=62436699 blks=1026 blk/s=51.3 txs=50139 tx/s=2.50k gas/s=425.90M buf=43.3MB/2.0GB stepsInDB=0.95 step=2940.0 alloc=31.6GB sys=44.3GB
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [WARN] [10-08|03:39:45.444] [agg] lookupVisibleFileByItsRange: file not found stepFrom=2936 stepTo=2938 _visible=0-2048;2048-2560;2560-2816;2816-2880;2880-2912;2912-2928;2928-2936;2936-2940; visibleFilesCount=8
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [CRIT] [10-08|03:39:45.444] storage file of steps 2936-2938 not found
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]:
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:45.444] [7/9 Execution] Done                     blk=62436699 blks=1026 blk/s=50.9 txs=50139 tx/s=2.48k gas/s=423.05M buf=43.3MB/2.0GB stepsInDB=0.00 step=2940.0 alloc=31.6GB sys=44.3GB
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [EROR] [10-08|03:39:45.445] Staged Sync                              err="[7/9 Execution] StateV3.Apply: hash sort failed: loadIntoTable : unfold: Branch failed: storage file not found"
Oct 08 03:39:45 rockx-mainnet-polygon-archive-mm-02 erigon[1878856]: [INFO] [10-08|03:39:45.995] [7/9 Execution] starting                 from=62435674 to=62446291 fromTxNum=4593769858 offsetFromBlockBeginning=0 initialCycle=true useExternalTx=false`
