### ISSUE TITLE
gnosis: pubKey ram use

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#12105]
<img width="557" alt="Screenshot 2024-09-26 at 15 20 33" src="https://github.com/user-attachments/assets/f30ce4c9-e10c-4584-8577-d9efe1cd3df1">

**Comment by Giulio2002** [comment]
this looks like mainnet

**Comment by Giulio2002** [comment]
Gnosis:

<img width="102" alt="Screenshot 2024-09-27 alle 00 45 29" src="https://github.com/user-attachments/assets/99d03a25-242b-4c55-96c4-1610ed49d9d7">

Mainnet:

<img width="225" alt="Screenshot 2024-09-27 alle 00 49 24" src="https://github.com/user-attachments/assets/5eab55a8-094d-4c4f-8f67-dbaafa292da4">


I did a PR that should decrease the size of this cache on gnosis by 18% on gnosis and 50% on mainneet.
