### ISSUE TITLE
New job to manually make docker image of chosen commit

### ISSUE THREAD

**Issue by JkLondon** [erigontech/erigon#12116]
# Rationale
Some platforms, like EthPandaOps tests, work exclusively with Docker images. When I need to fix something, I cannot test it directly until I create an image from my commit and publish it on DockerHub, or until it is merged into the main branch.

My proposal is to create a job that any developer (starting with the Erigon Team) can trigger. This job would:

Create a Docker image from a specific commit (entered manually). The image would be automatically deleted after n days to conserve storage space.
Enforce a usage limit per user to prevent overuse (for example, allowing 2-3 jobs per day, or whatever is deemed suitable).
I believe this should not be automated, as the developer should take full responsibility for the commit they choose to create an image from.

**Comment by JkLondon** [comment]
@lystopad

**Comment by lystopad** [comment]
It is now implemented.

Once you need just a docker image from some branch -- run `CI-CD build and deploy docker images based on the last commit in the target branch` workflow and specify your branch. 

If you need CI-CD which will continuously build and deploy docker images for some branch -- add code with settings for your branch as it is done [here](https://github.com/erigontech/erigon/blob/main/.github/workflows/ci-cd-main-branch-docker-images.yml#L65-L70).

Note: in any case it is nice to have `Dockerfile.release` same as in `main` branch.

**Comment by lystopad** [comment]
Done.
Changes merged to the main branch.
