### ISSUE TITLE
[e3-alpha4] fails to sync on bor-mainnet

### ISSUE THREAD

**Issue by optimiz-r** [erigontech/erigon#12190]
OS & Version: Linux Ubuntu 24.04

Erigon version: Both alpha4 (synced from scratch) and the latest main (both synced from scratch and updated) display this behavior.

Chain/Network: bor-mainnet

#### Actual behaviour

```
EROR] [10-03|08:01:40.464] Staged Sync                              err="[3/9 BorHeimdall] can't initialise validator sets: missing header persisting validator sets: (inside loop at 52000000)"
```

#### Steps to reproduce the behaviour

Sync from scratch

**Comment by Giulio2002** [comment]
We fixed this try `main`

**Comment by optimiz-r** [comment]
still getting it @Giulio2002 maybe it's not merged yet?

**Comment by andreyvg** [comment]
I have the same issue.
