### ISSUE TITLE
Caplin: Blob sidecars missing from specific block

### ISSUE THREAD

**Issue by dannynodies** [erigontech/erigon#12229]
#### System information

Erigon version: `erigon version 2.60.8`

OS & Version: Linux (Docker)

Commit hash: 

Erigon Command (with flags/config):       `--chain=sepolia --datadir=/root/.local/share/erigon --internalcl --port=30306 --authrpc.port=8551 --authrpc.jwtsecret=/root/.local/share/erigon/jwt.hex --authrpc.addr=0.0.0.0 --authrpc.vhosts=* --db.size.limit=3TB --private.api.addr=0.0.0.0:9090 --torrent.port=42069 --torrent.download.rate=1000mb --torrent.download.slots=6 --maxpeers=300 --p2p.allowed-ports=30306,30307,30308 --nat=extip:<redacted> --caplin.backfilling=true --caplin.backfilling.blob=true --caplin.backfilling.blob.no-pruning=true --caplin.archive=true --beacon.api=beacon,lighthouse,node,config --beacon.api.addr=0.0.0.0`

Consensus Layer: Caplin

Consensus Layer Command (with flags/config): `--caplin.backfilling=true --caplin.backfilling.blob=true --caplin.backfilling.blob.no-pruning=true --caplin.archive=true --beacon.api=beacon,lighthouse,node,config --beacon.api.addr=0.0.0.0`

Chain/Network: Sepolia

#### Expected behaviour

Blob sidecars present for the block

#### Actual behaviour

Empty list returned:
```
$ curl localhost:5555/eth/v1/beacon/blob_sidecars/5196840
{"data":[]}
```
Many other blocks do include sidecars

#### Steps to reproduce the behaviour

Sync node from scratch using v2.60.8 as archival node. Query `curl localhost:5555/eth/v1/beacon/blob_sidecars/5196840`

#### Backtrace

````
[backtrace]
````

**Comment by dannynodies** [comment]
Looks like this was my bad - blob downloading hadn't finished yet

**Comment by dannynodies** [comment]
Issue persists after blob downloading is completed. Referenced block is [6084518](https://sepolia.beaconcha.in/block/6084518) which should have 6 blobs

**Comment by Giulio2002** [comment]
It will be fixed during the next alpha version
