### ISSUE TITLE
Incorrect Gas Values in OTS Search Tests

### ISSUE THREAD

**Issue by tosettil-polimi** [erigontech/erigon#12248]
# Incorrect Gas Values in OTS Search Tests

## Description
The commit [e3: cumulative gas used: as a domain (#12012)](https://github.com/erigontech/erigon/commit/0c918959bd17ec664d0738c98972ebba1dff13b5) has introduced a bug that affects the gas values in the test cases for `ots_searchTransactionsAfter` and `ots_searchTransactionsBefore`.

## Affected Tests
- Test 14 in `ots_searchTransactionsAfter`
- Test 14 in `ots_searchTransactionsBefore`

[QA - RPC Integration Tests #161](https://github.com/erigontech/erigon/actions/runs/11028833482) 

## Error Details
The test results show a discrepancy in the `cumulativeGasUsed` and `gasUsed` values:

```diff
12c12
<         "cumulativeGasUsed": "0x1be92",
---
>         "cumulativeGasUsed": "0x1f92a",
15c15
<         "gasUsed": "0x1be92",
---
>         "gasUsed": "0x1f92a",
```

Expected values:

- `cumulativeGasUsed`:`0x1be92` (114322 in decimal)
- `gasUsed`:`0x1be92` (114322 in decimal)

Actual values:

- `cumulativeGasUsed`: `0x1f92a` (129322 in decimal)
- `gasUsed`: `0x1f92a` (129322 in decimal)

## Possible Cause
The commit may have altered the gas calculation logic or introduced changes that affect the transaction processing in the OTS 
 module.

## Suggested Next Steps

1. Review the changes introduced in the commit, focusing on gas calculation and OTS-related code
2. Verify if the new gas values are correct or if there's an unintended side effect
3. If confirmed as a bug, revert the problematic changes or implement a fix
4. Update the test cases if the new behaviour is intended

I'm currently investigating to figure out how to do an update to see if this is a bug or an expected change in the gas calculation.

**Comment by wmitsuda** [comment]
I'm debugging this one, will assign it to me
