### ISSUE TITLE
`EigenPod.getParentBlockRoot: invalid block root returned` when returning a trace

### ISSUE THREAD

**Issue by Uxio0** [erigontech/erigon#12242]
#### System information

Erigon version: `2.60.8`
OS & Version: Linux
Chain/Network: Mainnet

#### Expected behaviour

Traces should not contain errors, as Nethermind is doing. It looks related to https://eips.ethereum.org/EIPS/eip-4788

#### Actual behaviour

Traces contain errors.  Error is `EigenPod.getParentBlockRoot: invalid block root returned`

#### Steps to reproduce the behaviour

Call RPC with:

```json
{"method":"trace_transaction","params":["0x3bb48b222448fb9f17a1f1116930cf4598b42974b17eea433f4b4c4349244b0c"],"id":1,"jsonrpc":"2.0"}
```

**Comment by yperbasis** [comment]
Fixed by PR #12559 and will be released in v2.60.10.
