### ISSUE TITLE
Introducing Erigon Guru on Gurubase.io

### ISSUE THREAD

**Issue by kursataktas** [erigontech/erigon#12265]
Hello Erigon team,

I wanted to update you that I've added the Erigon Guru to Gurubase. Gurubase is a platform that aggregates open-source tools to help developers find information quickly. Erigon Guru uses the data from this repo and the data from [docs](https://erigon.gitbook.io/erigon) to answer questions. I hope you find it useful.

Here is the link to the Erigon Guru: https://gurubase.io/g/erigon

I believe Erigon users or new starters would find it useful to have a badge or a link to Gurubase in the README.md. I've prepared two examples below:

Example 1 - Just a badge: 
--
[![](https://img.shields.io/badge/Gurubase-ASK%20ERIGON%20GURU-006BFF)](https://gurubase.io/g/erigon)

Example 2 - Separate Section:
--
### ✨ Ask Erigon Guru
If you don’t want to get lost in the documentation, you can ask [Erigon Guru](https://gurubase.io/g/erigon) directly. It’s an AI that focuses on addressing your questions about Erigon.
[![](https://img.shields.io/badge/Gurubase-ASK%20ERIGON%20GURU-006BFF)](https://gurubase.io/g/erigon)

If you find it useful, I would be happy to open a PR for this.

Additionally, if you want me to disable Erigon Guru in Gurubase, just let me know that's totally fine.

**Comment by AskAlexSharov** [comment]
We blocking all github issues with external links for security reasons.

**Comment by kursataktas** [comment]
Would you like me to open this thread in the Discussion section or anywhere else?
