### ISSUE TITLE
Missing receipts on alpha3 polygon mainnet

### ISSUE THREAD

**Issue by Staking7pc** [erigontech/erigon#12292]
#### System information

Erigon version: `./erigon --version`
erigon version 3.00.0-alpha4-c0d9a2b9

OS & Version: Windows/Linux/OSX
Ubuntu 20.04

Commit hash:  c0d9a2b9

Erigon Command (with flags/config):

Consensus Layer:

Consensus Layer Command (with flags/config):

Chain/Network:  Polygon mainnet

#### Expected behaviour
    Erigon 2 had block receipts of all blocks even in full mode . so expecting same for erigon 3. The RPC call below to return receipts for a 50 days old block 

curl http://localhost:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getTransactionReceipt","params":["0xe0b75845d13ae12029c8dfef68488b3bf35347460fafdb3a15a5c7f884226288"],"id":1,"jsonrpc":"2.0"}'

#### Actual behaviour
 below RPC call returns error for a block which is 50 days old.

curl http://localhost:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getTransactionReceipt","params":["0xe0b75845d13ae12029c8dfef68488b3bf35347460fafdb3a15a5c7f884226288"],"id":1,"jsonrpc":"2.0"}'
  
`  {"code":-32000,"message":"getReceipts error: nonce too low: address 0x88928fF265a144Aef2c5e228D536D9E477A68CFC, tx: 1414671 state: 1457042"}`
  
#### Steps to reproduce the behaviour
SInce fresh from scrtach in erigon 3

#### Backtrace

````
[backtrace]
````

**Comment by antonis19** [comment]
@Staking7pc  could you provide the erigon command with the flags you used?

**Comment by awskii** [comment]
please check latest snapshot step inside `<datadir>/snapshots/domain`
So you have to do `ls` there and pick largest available range: like v1-account.3066-3067.kv - range here will be 3066-3067.
then you can do 
`./build/bin/erigon snapshots rm-state-snapshots --step=3066-10000 --datadir <>`
and at last, reset progress:
`./build/bin/integration stage_exec --reset --datadir <> --chain bor-mainnet`

We have machine with similar issue and after resetting RPC response seemd correct.

**Comment by awskii** [comment]
also make sure flag --prune.mode=archive is set.

**Comment by antonis19** [comment]
Can confirm that with `--prune.mode=archive` the RPC call works.

The issue seems to be when running a full node, and the historical state data necessary to generate the receipt is not available, so the latest data is (incorrectly) used instead. This is an improvement that needs to be implemented for clarity in the error.
