### ISSUE TITLE
Possible regression on multiple rpc methods re: future block number

### ISSUE THREAD

**Issue by wmitsuda** [erigontech/erigon#12323]
Context: I'm investigating some regressions on ots APIs based on the feedback of rpc-tests.

This issue is based on my analysis of test_09: https://github.com/erigontech/rpc-tests/blob/main/integration/mainnet/ots_hasCode/test_09.json

That tests calls `ots_hasCode` with a contract address, but with a future block number.

The expected behavior is to the future block number to behave like you are querying the latest block, i.e. plain state.

That assumption was broken recently on e3.

Apparently a regression was introduced in commit https://github.com/erigontech/erigon/commit/7ddca95c2044b5010ba21192f570929e99fc9606#diff-d9ca43c5954aa50c7af3a4ee1b6bdffc146d2494b3b68b88f80f79366dc73f68R113

on `rpchelper`, the new check on line 113, since you are querying a future block number, there is no canonical hash.

You can observe the difference by querying e2 and e3 nodes using the cast command:

```
cast rpc -r <e2-node-url> ots_hasCode 0xdAC17F958D2ee523a2206206994597C13D831ec7 0xffffffff
true
```

```
cast rpc -r <e3-node-url> ots_hasCode 0xdAC17F958D2ee523a2206206994597C13D831ec7 0xffffffff
false
```

```
cast rpc -r <e3-node-url> ots_hasCode 0xdAC17F958D2ee523a2206206994597C13D831ec7 latest
true
```

However, I noticed it broke not only for ots APIs, but for all methods that allow a block number, for example, see `eth_getBalance`:

```
cast rpc -r <e2-node-url> eth_getBalance 0xdAC17F958D2ee523a2206206994597C13D83
1ec7 0xffffffff
"0x1"
```

```
cast rpc -r <e3-node-url> eth_getBalance 0xdAC17F958D2ee523a2206206994597C13D831ec7 0xffffffff
"0x0"
```

```
cast rpc -r <e3-node-url> eth_getBalance 0xdAC17F958D2ee523a2206206994597C13D831ec7 latest
"0x1"
```

So, now I'm confused: there was indeed a change of semantics from E2 -> E3. However, I'm not sure if this is the correct behavior (couldn't find what is the "correct" behavior in the RPC spec), should querying a future, non-existent yet block assume the same semantics as "latest"? If that's the case, the commit I referenced here introduced a regression and we should fix it.

Otherwise we should correct the rpc-tests.

BTW: that was caught by ots_hasCode tests, there are no correspondent tests for eth_getBalance and others, maybe should consider adding it after we reach a conclusion here.

**Comment by AskAlexSharov** [comment]
let's keep compatibility with E2 as much as we can - to simplify user's migration: https://github.com/erigontech/erigon/pull/12329
