### ISSUE TITLE
Update Chiado snapshots regularly

### ISSUE THREAD

**Issue by yperbasis** [erigontech/erigon#12439]
https://github.com/erigontech/erigon-snapshot/blob/main/chiado.toml was updated last time in April

**Comment by michelemodolo** [comment]
I just started erigon (`commit 81fc25776208127e38aa3f93067ef13bb7db6365 29 OCT 2024`) on the new chiado snapshotter. Let's see how it behaves.

**Comment by michelemodolo** [comment]
1) snapshots generation from genesis (`--no-downloader`) didn't succeed after 4 days 
2) E3 got restarted using the downloader, which currently seems stuck (many files are at 0% downloading)
3) @taratorio has been working on making e3/caplin work on chiado too so he was given admin access on this snapshotter

**Comment by taratorio** [comment]
@michelemodolo I'll have the Chiado snapshotter ready for you end of today, working on it atm

**Comment by michelemodolo** [comment]
Thank you @taratorio 

The automation was instated for chiado too and ran a few minutes ago like a charm. 
Result: https://erigon3-v1-snapshots-chiado.erigon.network/manifest.txt

I formally put this task "in review" for @yperbasis (who raised it): if you're fine with that just flag it as "Done".

**Comment by yperbasis** [comment]
Thank you @michelemodolo , @taratorio
