### ISSUE TITLE
Docker Image v2.60.9 is missing in dockerhub

### ISSUE THREAD

**Issue by jasonyic** [erigontech/erigon#12539]
code base v2.60.9 has been release for 5 days, but docker image `v2.60.9` is not available in dockerhub yet?

**Comment by lystopad** [comment]
Hi, @jasonyic 

Probably you are looking in the former dockerhub repo.

You can pull latest released image with the following command:

`docker pull erigontech/erigon:v2.60.9
`
Note, latest images pushed to "erigontech/" docker repository.

It is now multi-platform docker image which supports 3 architecture variants: linux/arm64, linux/amd64 and linux/amd64v2.

Best regards
@lystopad

**Comment by jasonyic** [comment]
did not know the docker repo has been changed to `erigontech`. thank you for the update.
