### ISSUE TITLE
Alpha5 binary crash arm64

### ISSUE THREAD

**Issue by blxdyx** [erigontech/erigon#12556]
#### System information

Erigon version: `./erigon --version v3.0.0-alpha5`  

OS & Version: Linux(arm64)

Commit hash: 

Erigon Command (with flags/config): `./build/bin/erigon --datadir=./data --chain=sepolia --log.console.verbosity=4 --port=30304 --http.port=8546 --authrpc.port=8552 --torrent.port=42068 --private.api.addr=127.0.0.1:9092 --http --ws --http.api=eth,debug,net,trace,web3,erigon`

Consensus Layer:

Consensus Layer Command (with flags/config):

Chain/Network: 

#### Steps to reproduce the behaviour

Download binary from https://github.com/erigontech/erigon/releases/download/v3.0.0-alpha5/erigon_v3.0.0-alpha5_linux_arm64.tar.gz

#### Backtrace

[crash.log](https://github.com/user-attachments/files/17584694/crash.log)

**Comment by lystopad** [comment]
@blxdyx , hi
could you, please, let us know which OS are you using exactly and your CPU?
Does erigon work if you build it on your OS on your own (of course, using git tag "v3.0.0-alpha5" for checkout) ?

**Comment by lystopad** [comment]
@blxdyx thanks.
Could you, please, try to run docker image "erigontech/erigon:v3.0.0-alpha5" (multi-platform image) with your parameters. Data-dir could be used as a volume.

There is a progress with fix, but it still require some more time.

**Comment by AskAlexSharov** [comment]
seems fixed: https://github.com/erigontech/erigon/issues/12570#issuecomment-2492369474 
closing for now. feel free to re-open if need.
