### ISSUE TITLE
re-gen manifest.txt after TTL deletes

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#12573]
We have CI linter that checks invariant: that all files declared in manifest.txt must exists
After TTL cleanup this check start failing on CI. 
Is it easy to re-gen manifest.txt after TTL cleanup? Do you have better ideas?

Example:
```
 go run ./cmd/downloader manifest-verify --chain=mainnet --webseed=https://erigon3-v1-snapshots-mainnet.erigon.network --log.console.verbosity=4
```

```
v1-020560-020561-transactions.seg
v1-020560-020561-transactions.seg.torrent
SEED [BAD] https://erigon3-v1-snapshots-mainnet.erigon.network

-----------------------REPORTS OVERVIEW--------------------------
## REPORT [BAD] on https://erigon3-v1-snapshots-mainnet.erigon.network
 - manifest exist: true
 - missing torrents (files without torrents): 0
 - dangling (data file not found) torrents: 1
 - invalid ETags format: 0/5669
 - ETag fetch failed: 248/5669
```
https://github.com/erigontech/erigon/actions/runs/11623979816/job/32371866053?pr=12572

**Comment by michelemodolo** [comment]
@AskAlexSharov I implemented it. Next time the automation will be triggered (chain by chain) this inconvenience should disappear.
