### ISSUE TITLE
Erigon3 debug_traceCallMany "method handler crashed" error

### ISSUE THREAD

**Issue by s84-dev** [erigontech/erigon#12589]
System information
Erigon version: ./erigon3 -- main branch [f617c433fd255945c586e6aba58288ad2bb86f7d]

OS & Version: Linux

Commit hash: f617c433fd255945c586e6aba58288ad2bb86f7d
Erigon Command (with flags/config):

datadir : '/mnt/evm_node/data/mainnet'
prune.mode : 'archive'
prune.distance : 2048
prune.distance.blocks : 2048
chain : 'mainnet'
port : 30303
http.port : 8545
http.addr : 0.0.0.0
authrpc.port : 8551
torrent.port : 42069
http.vhosts : 'any'
http.corsdomain : '*'
private.api.addr : 127.0.0.1:9090
rpc.batch.limit : 200
http : true
ws : true
ws.compression : true
ws.port : 8546
http.api : ["eth","debug","net","trace","web3","erigon","admin"]
torrent.download.rate : '512mb'

Consensus Layer: caplin

Consensus Layer Command (with flags/config):

Chain/Network: mainnet

Expected behaviour
debug_traceCallMany execute transaction on the state of pre-transaction

Actual behaviour
{"jsonrpc":"2.0","id":1,"result":[[null,"error":{"code":-32000,"message":"method handler crashed"}}

Steps to reproduce the behaviour
execute the following code:

```
const simulate_address = "0x***57c3";
const weth_holder = "0x***7806";

const transfer_weth_txn = {
    from: weth_holder,
    to: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    data: '0xa9059cbb' + simulate_address.slice(2).padStart(64, '0') + BigInt(1e20).toString(16).padStart(64, '0'),
}

const balanceOf_weth_txn = {
    from: simulate_address,
    to: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    data: '0x70a08231' + simulate_address.slice(2).padStart(64, '0'),
}

async function test() {
    const txns = [
        balanceOf_weth_txn, transfer_weth_txn, balanceOf_weth_txn
    ];

    const traceConfig =
    {
        "tracer": "callTracer",
        "tracerConfig": {
            "onlyTopCall": true,
        }
    }

    const requestBody = {
        "jsonrpc": "2.0",
        "method": "debug_traceCallMany",
        "params": [
            [
                {
                    "transactions": txns,
                    // "blockOverride": {
                    //     "blockNumber": nextBlockNumberHex,
                    //     "timestamp": '0x' + nextTimeStamp.toString(16)
                    // }
                }
            ],
            {
                // "blockNumber": blockNumberHex,
                "blockNumber": 'latest',
                "transactionIndex": -1
            },
            traceConfig
        ],
        "id": 1
    }

    console.log('simulate_http_url:', hre.network.config.simulate_http_url);
   const res = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'header': 'content-type: application/json'
        },
        body: JSON.stringify(requestBody),

    });

    const resJson = await res.json();

   console.log(resJson);
}

test().then(() => {
console.log('test finished');
}).catch(err => {
console.log('test failed:', err);
});
```

it trace_callMany with 3 transactions: [balanceOf, transfer, balanceOf ]

the third transaction's output should reflect the transfer result as '0x0000000000000000000000000000000000000000000000056bc75e2d63100000'

while erigon3 return
{"jsonrpc":"2.0","id":1,"result":[[null,"error":{"code":-32000,"message":"method handler crashed"}}

**Comment by AskAlexSharov** [comment]
thank you. fixed by: https://github.com/erigontech/erigon/pull/12593

**Comment by AskAlexSharov** [comment]
feel free to re-open if need
