### ISSUE TITLE
E3 'debug_traceCallMany' api param 'transactionIndex' not work

### ISSUE THREAD

**Issue by s84-dev** [erigontech/erigon#12653]
#### System information

Erigon version: 3.00.0-alpha5-3c9ffb69

OS & Version: linux

Commit hash:  3c9ffb69c124074e917e85c997a2e9027154a50e 

Erigon Command (with flags/config):

> datadir : '/mnt/evm_node/data/mainnet'
prune.mode : 'archive'
prune.distance : 2048
prune.distance.blocks : 2048
chain : 'mainnet'
port : 30303
http.port : 8545
http.addr : 0.0.0.0
authrpc.port : 8551
torrent.port : 42069
http.vhosts : 'any'
http.corsdomain : '*'
private.api.addr : 127.0.0.1:9090
rpc.batch.limit : 200
http : true
ws : true
ws.compression : true
ws.port : 8546
http.api : ["eth","debug","net","trace","web3","erigon","admin","txpool"]
torrent.download.rate : '512mb'
log.dir.disable : true

Consensus Layer: caplin

Desc:
when use debug_traceCallMany, the 'transactionIndex' is default -1, means running at end of the block. 
Now txns is running at beginning of the block,  no matter what value of 'transactionIndex' is set

testcase:

Chain/Network: mainnet

#### Expected behaviour
we have a transaction which change the balance of EOA.    when simulate an transaction to return the balance of account, running with 'transactionIndex = -1' should return the changed value.

#### Actual behaviour
it return the value before change, no matter transactionIndex = 0 or -1

#### Steps to reproduce the behaviou

1. mine an transaction which change the balance of EOA.

2. debug_traceCallMany with 
                    {
                        "blockNumber": blockNumberHex,
                        "transactionIndex": -1
                    },
should return the changed balance
but it return the unchanged balance 

#### Backtrace

````
[backtrace]
````

**Comment by sstonehu** [comment]
the bug still exits in the new branch [061ba77](https://github.com/erigontech/erigon/pull/12663/commits/061ba77ab04ef0332d2d8bbfce21f6ed7e38d7c9)

**Comment by sstonehu** [comment]
this bug was not fixed.

`

const simulate_address = '0xfba0014d3a9dbe8a0cda6affd3da7b541a1ec32f';
const proxy_address = '0xdf8adfe10d4a4d9f0fc4d3e377a6e8d5730eb40c';

const balanceOf_weth_txn = {
    from: simulate_address,
    to: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    data: '0x70a08231' + proxy_address.slice(2).padStart(64, '0'),
}


async function main() {

    const blockNumber = 21140240;
    const blockNumberHex = '0x' + blockNumber.toString(16);

    const txns = [
        balanceOf_weth_txn,
    ];

    const traceConfig =
    {
        "tracer": "callTracer",
        "tracerConfig": {
            "onlyTopCall": true,
        }
    }

    const requestBody = {
        "jsonrpc": "2.0",
        "method": "debug_traceCallMany",
        "params": [
            [
                {
                    "transactions": txns,
                }
            ],
            {
                "blockNumber": blockNumberHex,
                "transactionIndex": -1
                // "transactionIndex": 0
            },
            traceConfig
        ],
        "id": 1
    }

    const url = hre.network.config.debug_http_url;

    console.log(url);
    const res = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'header': 'content-type: application/json'
        },
        body: JSON.stringify(requestBody),

    });
    console.log(res);
    const writeRes = await res.json();

    console.log(`writeRes:`, writeRes);
    console.log(writeRes.result);
    console.log(writeRes.result[0][0].output);
    // console.log(writeRes.result[0][0].calls);
    // console.log(writeRes.result[0][1].calls);


}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});


function decodePreState(preStates, target_address) {
    const accessList = [];
    for (const address in preStates) {
        if (address.toLowerCase() === target_address.toLowerCase() ||
            address.toLowerCase() === EOA.toLowerCase()
        ) continue;
        if (!preStates?.[address]?.code) continue;
        const storage = preStates?.[address]?.storage;
        if (storage) {
            const storageKeys = Object.keys(storage);
            accessList.push({
                address: address,
                storageKeys: storageKeys
            });
        } else {
            // delegatecall
            accessList.push({
                address: address,
                storageKeys: []
            });
        }
    }

    // console.log('accessList:', accessList);
    return accessList;
}`

the output should reflect the changed balance: 
0x0000000000000000000000000000000000000000000000003eb4a924ac778199

but its 
0x0000000000000000000000000000000000000000000000003e050eba2c588c99

which is same as unchanged value, equal to output when transactionIndex = 0
