### ISSUE TITLE
Caplin: Chiado chain is borked

### ISSUE THREAD

**Issue by Giulio2002** [erigontech/erigon#12669]
**Description:**  
Chiado Chain nodes are failing to sync, with nodes either stalling or not progressing at all.

### Steps to Reproduce
1. Set up a node per Chiado Chain documentation.
2. Attempt to sync with the network.
3. Sync stalls or fails.

### Expected vs. Actual
- **Expected:** Node syncs to the latest block.
- **Actual:** Node fails to sync.

### Reproduction

`./build/bin/caplin --chain=chiado`

**Comment by yperbasis** [comment]
Might be related to #12439
