### ISSUE TITLE
git_tag in Erigon release on docker hub is incorrect

### ISSUE THREAD

**Issue by yperbasis** [erigontech/erigon#12661]
See https://github.com/erigontech/erigon/issues/12525#issuecomment-2459962716 <- the commit is right, but the tag is wrong

It's important to solve it since otherwise it's very confusing. If it's not feasible to solve the issue, it's better to remove `git_tag` altogether to avoid confusion.

**Comment by lystopad** [comment]
Done in PR https://github.com/erigontech/erigon/pull/12721
