### ISSUE TITLE
Erigon node fails when starting in version v2.60.9

### ISSUE THREAD

**Issue by diegopazosrego** [erigontech/erigon#12710]
#### ISSUE

In our Kubernetes environment and  the configuration of :
` securityContext - readOnlyRootFilesystem: true`

In the past version 2.60.8 + lighthouse v.5.3.0 it works success, but in the new version it fails:

`[EROR] [11-12|09:41:17.309] catch panic                              err="mkdir /.local: read-only file system" stack="[main.go:29 panic.go:770 rw_dir.go:34 dirs.go:79 flags.go:1386 flags.go:1368 node.go:96 main.go:59 make_app.go:54 command.go:276 app.go:333 app.go:307 main.go:34 proc.go:271 asm_amd64.s:1695]"`

#### System information

Erigon version: v2.60.9

OS & Version: Linux

Erigon Command (with flags/config):
```
            "--chain=mainnet"
            "--db.size.limit=8TB",
            "--metrics",
            "--metrics.addr=0.0.0.0",
            "--metrics.port=6060",
            "--private.api.addr=0.0.0.0:9089",
            "--pprof",
            "--pprof.addr=0.0.0.0",
            "--pprof.port=6061",
            "--snapshots=true",
            "--torrent.upload.rate=500mb",
            "--torrent.download.rate=1200mb", 
            "--http",
            "--http.api=engine,net,eth,debug,trace,txpool,web3",
            "--http.addr=0.0.0.0",
            "--http.port=8545",
            "--http.vhosts=*",
            "--http.corsdomain=*",
            "--authrpc.addr=0.0.0.0",
            "--authrpc.jwtsecret=/mnt/jwtsecret/jwtsecret",
            "--authrpc.port=9545",
            "--authrpc.vhosts=*",
            "--prune=",
```

Consensus Layer:

`lighthouse v5.3.0`

Consensus Layer Command (with flags/config):
```
            "--chain=mainnet",
            "--db.size.limit=8TB", 
            "--metrics",
            "--metrics.addr=0.0.0.0",
            "--metrics.port=6060",
            "--private.api.addr=0.0.0.0:9089",
            "--pprof",
            "--pprof.addr=0.0.0.0",
            "--pprof.port=6061",
            "--snapshots=true",
            "--torrent.upload.rate=500mb",
            "--torrent.download.rate=1200mb", 
            "--http",
            "--http.api=engine,net,eth,debug,trace,txpool,web3",
            "--http.addr=0.0.0.0",
            "--http.port=8545",
            "--http.vhosts=*",
            "--http.corsdomain=*",
            "--authrpc.addr=0.0.0.0",
            "--authrpc.jwtsecret=/mnt/jwtsecret/jwtsecret",
            "--authrpc.port=9545",
            "--authrpc.vhosts=*",
            "--prune=", 

```
Chain/Network: mainnet

#### Steps to reproduce the behaviour

Start the node and it fails when its starting 

#### Backtrace

````
[EROR] [11-12|09:41:17.309] catch panic                              err="mkdir /.local: read-only file system" stack="[main.go:29 panic.go:770 rw_dir.go:34 dirs.go:79 flags.go:1386 flags.go:1368 node.go:96 main.go:59 make_app.go:54 command.go:276 app.go:333 app.go:307 main.go:34 proc.go:271 asm_amd64.s:1695]"
````

**Comment by lystopad** [comment]
@diegopazosrego , hi
Could you, please, let me know which docker image you use with its digest?

In your configuration snippets I see your own configuration path "/mnt" which might be an attempt to run erigon container with some your local configuration changes or your own volumes. In this case it is important to know how you configure your Kubernetes environment. Please, provide your configuration as well (of course without exposing any secrets/passwords/etc).

Best regards
@lystopad

**Comment by diegopazosrego** [comment]
Hi @lystopad ! 
The issue is solved, we only had to add the --datadir parameter to specify the right path for Erigon 

`"--datadir=/home/erigon/.local/share/erigon",`
