### ISSUE TITLE
Minimal: support more history of 

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#12749]
we reduced `FullImmutabilityThreshold` https://github.com/erigontech/erigon/pull/12748 for chain-tip perf, but `--prune.mode=minimal` now doesn't have enough historical data (maybe it's ok?) to server recent history RPC requests.

**Comment by Giulio2002** [comment]
its okay - it has 100k

**Comment by AskAlexSharov** [comment]
> its okay - it has 100k of history

I reduced it to improve chain-tip perf: https://github.com/erigontech/erigon/pull/12748/files
