### ISSUE TITLE
Ethereum: trace_block: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by AdamRylski** [erigontech/erigon#12899]
#### System information

Erigon version: 
```
{
    "id": 67,
    "jsonrpc": "2.0",
    "result": "erigon/2.60.10/linux-amd64/go1.22.8"
}
```

Chain/Network: Ethereum mainnet

#### Expected behaviour
Erigon should respond with proper block traces for query
```
{
  "jsonrpc": "2.0",
  "method": "trace_block",
  "params": [
    "0x144c724"
  ],
  "id": 1
}
```

#### Actual behaviour
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "first run for txIndex 59 error: insufficient funds for gas * price + value: address 0x0b92619DdE55C0cbf828d32993a7fB004E00c84B have 1217128811150211237 want 1217129447495431237"
    }
}
```

#### Steps to reproduce the behaviour
```
curl --location --request POST 'your-awesome-node' --header 'Content-Type: application/json' --data-raw '{
  "jsonrpc": "2.0",
  "method": "trace_block",
  "params": [
    "0x144c724"
  ],
  "id": 1
}'
```

Similar issue was raised for Polygon in 2022 https://github.com/erigontech/erigon/issues/4784

**Comment by whidrasl** [comment]
same.
Also same issue was a month earlier:
https://github.com/erigontech/erigon/issues/12432

**Comment by whidrasl** [comment]
You can use method `web3_clientVersion` to check node version by RPC call

**Comment by AdamRylski** [comment]
> You can use method web3_clientVersion to check node version by RPC **call**

That's what I posted in the `Erigon version:` section :)
