### ISSUE TITLE
eth_getTransactionReceipt on v3.0.0-alpha5 20X+ slower than Geth or Erigon 2.0 ? 

### ISSUE THREAD

**Issue by journeytosilius** [erigontech/erigon#12892]
#### System information

* (HEAD detached at v3.0.0-alpha5)
  main

Ubuntu server 24

#####################

Just ran my backend with v3.0.0-alpha5 and eth_getTransactionReceipt is 20X slower or more. Before it takes about 1-3 seconds to parse 60 blocks and now it takes 1 minute.  I believe also slower than Erigon 2.0 ?

I read here there is a similar problem : https://github.com/erigontech/erigon/issues/11090

How can I fix this or tune it ?

**Comment by awskii** [comment]
Can you please provide query you running for us to assess?

**Comment by JkLondon** [comment]
yep, exactly working on it in https://github.com/erigontech/erigon/pull/12424
