### ISSUE TITLE
Docker image erigontech/erigon:v2.60.10 has UID 100 by default

### ISSUE THREAD

**Issue by whidrasl** [erigontech/erigon#12900]
Start erigon from docker image `docker run erigontech/erigon:v2.60.10`
Then inside `docker exec -it`:
`erigon@0581f299b363:~$ id`
`uid=100(erigon) gid=1000(erigon) groups=1000(erigon)`

Expecting uid=1000 (as documented in README). Also in `erigontech/erigon:latest` uid=100 too

**Comment by lystopad** [comment]
@whidrasl , hi
Thank you for pointing to the issue 👍 .
I reconfigured our Dockerfile and coming release will have correct UID and GID equal `1000` for `erigon` user.
