### ISSUE TITLE
What's the fastest way to get earlier pruning data on already started node?

### ISSUE THREAD

**Issue by fridary** [erigontech/erigon#12950]
**Erigon version:** `erigon version 2.59.3-088fd8ef`
**OS & Version:** Ubuntu 20.04.6 LTS, CPU E5-2695 v4, 36 cores, 192 Gb RAM
**Disk:** NVMe HPE MT006400KWHAE 6.4 Tb 
**Erigon Command (with flags/config):** `ExecStart=/home/sirjay/erigon/build/bin/erigon --datadir=/disk_sde/erigon --ws --http.api=eth,erigon,engine,web3,net,debug,trace,txpool --authrpc.jwtsecret=/home/sirjay/erigon/jwtsecret --prune.h.before=13916166 --prune.r.before=13916166 --prune.t.before=13916166 --prune.c.before=13916166 --torrent.download.rate=128mb --rpc.batch.limit=5000`
**Chain/Network:** mainnet

As you can see, I started a half year ago erigon node with pruning from 13916166 block (2022 year). Now I need earlier data to 2020 year and I have read there is no way to do that just changing prune flag and reload.
Erigon node I remember was syncing 2 weeks, so, is there any other options that I can speed up syncing with having already loaded current pruned node? Any ideas I can do? Maybe install erigon v3?

**Comment by AskAlexSharov** [comment]
- we have command to force change prune flag - but we never testing this scenario, so i don't know will it work or not. and likely can't debug problems on hacked node. 
- there are 3-rd-party providers which for some money - providing downloadable archives of synced Erigon2. 
- we have node-providers in our discord - you may ask then to share for you synced archive Erigon2 backup (they for sure have many). 
- Erigon3 - i advise you to try it. Especially if you can use it for some limited use-case. Use `main` git branch. We slowly moving towards `beta1` release there. And your feedback will be very useful for us. What changed: https://github.com/erigontech/erigon?tab=readme-ov-file#erigon3-changes-from-erigon2

**Comment by fridary** [comment]
@AskAlexSharov thank you for answer
> if you can use it for some limited use-case. Use main git branch. We slowly moving towards beta1 release there

Can you clarify please, `beta1` is erigon v3? I see on release page only `v3.0.0-alpha5` last version. Or will it be to install like:
`git clone --branch release/v3.0.0-beta1 --single-branch https://github.com/erigontech/erigon.git` ?

**Comment by AskAlexSharov** [comment]
For erigon3 use `main` git branch.
