### ISSUE TITLE
p2p in e3 - too many peers

### ISSUE THREAD

**Issue by totoCZ** [erigontech/erigon#12963]
I tested e3 with Caplin and max peers set to some reasonable value (50 or so) but the peers kept growing over 100 and it consumes too much network resources, much more than grandine. It was an order of magnitude (100 vs 10 Mbit).
I read in some other client bug tracker that the libp2p implementation of this limit is flawed.
If I set 50, it needs to do a hard limit on peers, or limit the bandwidth more efficiently.
v3.0.0-alpha5
I already deleted the client so I'm only writing this from memory.
EL part was working fine.

**Comment by AskAlexSharov** [comment]
show logs

**Comment by AskAlexSharov** [comment]
- try switch to `main` git branch
- show logs

**Comment by Giulio2002** [comment]
have you tried `--caplin.max-peer-count`?

**Comment by Giulio2002** [comment]
https://github.com/erigontech/erigon/pull/12999

**Comment by Giulio2002** [comment]
<img width="218" alt="Screenshot 2024-12-04 alle 21 25 51" src="https://github.com/user-attachments/assets/d92de6fc-e032-4ab4-a4df-d1a0203f16fc">

anyway the reason why tweaking caplin did not work is simple - it is not caplin's fault. average bandwidth usage for cl standalone is a < 3MB/sec on maxed out peers

**Comment by Giulio2002** [comment]
anyway thanks for the issue because due to this, I found a way better bandwidth limiting for caplin ;)
