### ISSUE TITLE
Caplin: avoid runtime change NetworkId

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#13016]
i see next things in code 
```
config.NetworkId = clparams.CustomNetwork // Force custom network
```
it looks like hack (probably to force some next code behave as expected). but probably we can avoid it. 
let's create config objects at start of app and then don't mutate them in runtime or objects constructors.

**Comment by Giulio2002** [comment]
i will keep this for now. @domiwei is testing pectra and while ugly it works
