### ISSUE TITLE
RunCaplinService: to set freezeCfg.ChainName field

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#13017]
- it's empty now and i not found way to fill it

**Comment by AskAlexSharov** [comment]
> sorry how does it fail - it does not for me??

It doesn’t fail - but it silently makes all files “non-seedable” and “non-frozen”. Look at “Seedable” and “Frozen” helper funcs. 

You can see example fail: https://github.com/erigontech/erigon/pull/13018#issue-2721964392

**Comment by Giulio2002** [comment]
oooh ok - no it will be fixed in one of my upcoming PRs then
