### ISSUE TITLE
Support the `debug_getRawReceipts` method

### ISSUE THREAD

**Issue by TimTinkers** [erigontech/erigon#13036]
# Rationale

Recently I synced an Erigon 3 archive node because I am very excited about the work you are all doing and I wanted to experiment with running one. Today I learned that Erigon does not support `debug_getRawReceipts` https://x.com/mysticryuujin/status/1777786021876273540. Previously I relied on [geth, which has this method](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debuggetrawreceipts). 

This endpoint is used somewhere by [op-succinct](https://github.com/succinctlabs/op-succinct) or one of its dependencies as part of generating proofs. I am afraid I do not have much more detail on the specifics there. It would nice to have another client able to support my usecase, however.

# Implementation

I unfortunately have neither an understanding of how this feature works nor the ability to implement it myself.

**Comment by AskAlexSharov** [comment]
Looks very simple task

**Comment by AskAlexSharov** [comment]
added: https://github.com/erigontech/erigon/pull/13045

**Comment by TimTinkers** [comment]
I have updated my node and this looks good to me!
