### ISSUE TITLE
eth_estimateGas  error: too many arguments, want at most 2

### ISSUE THREAD

**Issue by rayn316** [erigontech/erigon#13084]
#### System information

Erigon version: v2.60.10

OS & Version: Linux

Commit hash: 

Erigon Command (with flags/config):  `/node/archive/ethereum/bin/erigon --datadir=/node/archive/ethereum/erigon --chain=mainnet --db.size.limit=8TB --prune=disabled --log.dir.verbosity error --authrpc.jwtsecret=/node/archive/ethereum/erigon/jwt.hex --rpc.gascap=600000000 --rpc.evmtimeout=30s --rpc.batch.limit=100 --rpc.returndata.limit=104857600 --txpool.globalslots 1000000 --txpool.globalbasefeeslots 3000000 --txpool.globalqueue 3000000 --http=true --http.api eth,net,web3,debug,trace,txpool --http.addr 0.0.0.0 --http.corsdomain * --http.vhosts * --ws --authrpc.addr localhost --port=21300 --http.port 21301 --ws.port 21302 --private.api.addr= --authrpc.port=21303 --torrent.port=21304 --p2p.allowed-ports 21306 --diagnostics.disabled`

Consensus Layer:

Consensus Layer Command (with flags/config):

Chain/Network: 

#### Expected behaviour
Return normal information: geth info
```
curl http://127.0.0.1:31301 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{
  "jsonrpc": "2.0",
  "method": "eth_estimateGas",
  "params": [
    {
      "from": "0x0000000000000000000000000000000000000001",
      "to": "0x0000000000000000000000000000000000000002",
      "value": "0x38d7ea4c68000",
      "data": "0x"
    },
    "latest",
    {
      "0x0000000000000000000000000000000000000002": {
        "balance": "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "code": "0x6001600101",
        "nonce": "0x0"
      }
    }
  ],
  "id": 1
}'

{"jsonrpc":"2.0","id":1,"result":"0x52e9"}
```

#### Actual behaviour
erigon returns error
```
curl http://127.0.0.1:21301 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{
  "jsonrpc": "2.0",
  "method": "eth_estimateGas",
  "params": [
    {
      "from": "0x0000000000000000000000000000000000000001",
      "to": "0x0000000000000000000000000000000000000002",
      "value": "0x38d7ea4c68000",
      "data": "0x"
    },
    "latest",
    {
      "0x0000000000000000000000000000000000000002": {
        "balance": "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "code": "0x6001600101",
        "nonce": "0x0"
      }
    }
  ],
  "id": 1
}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"too many arguments, want at most 2"}}
```

There is a PR that may be related to this issue
https://github.com/erigontech/erigon/pull/11743

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/erigontech/erigon/pull/13090
