### ISSUE TITLE
Caplin - Beacon API SSE stream disconnecting

### ISSUE THREAD

**Issue by eth2353** [erigontech/erigon#13099]
#### System information

Erigon version: `3.00.0-alpha6-f22317ef`

OS & Version: Linux

Commit hash: f22317ef

Erigon Command (with flags/config): N/A

Consensus Layer: Caplin

Consensus Layer Command (with flags/config): N/A

Chain/Network: Gnosis Chain

#### Expected behaviour

The connection to the SSE stream is stable and stays open.

#### Actual behaviour

Caplin's Beacon API SSE stream keeps disconnecting, frequently and regularly, every ~26 seconds.

#### Steps to reproduce the behaviour

`curl http://<host>:<port>/eth/v1/events?topics=head\&topics=chain_reorg`

After a while the connection is terminated with curl showing `curl: (18) transfer closed with outstanding read data remaining`.

**Comment by eth2353** [comment]
This one is not fixed, the connection closes even more frequently on the latest master, every ~6ish seconds.

**Comment by Giulio2002** [comment]
Are you sure you can still reproduce it with `curl`? I cannot get `curl: (18) transfer closed with outstanding read data remaining` anymore

**Comment by Giulio2002** [comment]
oh - it was a silly mistake

**Comment by Giulio2002** [comment]
will be fixed (soon): https://github.com/erigontech/erigon/pull/13112

**Comment by eth2353** [comment]
Confirming that fixes it 👍 Thanks!
