### ISSUE TITLE
Latest docker image is broken

### ISSUE THREAD

**Issue by tornadocontrib** [erigontech/erigon#13092]
#### System information

Erigon version: alpha6

```
exec /usr/local/bin/erigon: no such file or directory
```

**Comment by lystopad** [comment]
@tornadocontrib , hi
Thank you for the issue.

Please, try following temporary docker image (it will be removed in couple of days) 
```
docker pull erigontech/erigon:v3.0.0-testing-workflow4
```

This image based on Debian Bookworm image and contains all needed libraries to run erigon.
Please, provide your feedback.

**Comment by koraykoska** [comment]
@lystopad it works. Can you please deploy it to a proper tag?

**Comment by tornadocontrib** [comment]
@lystopad Seems like it has been fixed, when would the release tag being updated?

**Comment by michelemodolo** [comment]
@VBulikov please review

**Comment by lystopad** [comment]
@tornadocontrib , @koraykoska -- I updated docker image and now `erigontech/erigon:v3.0.0-alpha6` should work fine on any architecture.
