### ISSUE TITLE
Add linter for Temporal interface

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#13123]
1. find existing linter (in golnagcilint) which will catch such things: https://github.com/erigontech/erigon/pull/13120/files (i'm sure it exists).
2. add in `rules.go` match for `BeginTemporalRo` (and `rw`).

**Comment by sudeepdino008** [comment]
added nilness linter - https://github.com/erigontech/erigon/pull/13146
it doesn't do alingse's nilnesserr; should we wait for alingse to add it to golanci-lint? Same option is not present.  @AskAlexSharov

**Comment by AskAlexSharov** [comment]
> it doesn't do alingse's nilnesserr; should we wait for alingse to add it to golanci-lint? Same option is not present.

sorry, i don't understand the sentence

**Comment by sudeepdino008** [comment]
> > it doesn't do alingse's nilnesserr; should we wait for alingse to add it to golanci-lint? Same option is not present.
> 
> sorry, i don't understand the sentence

I mean to catch the issue like https://github.com/erigontech/erigon/pull/13120/files, we need the new `nilnesserr` linter, which is still in development and not added to golangci-lint. The author said it'll be added once testing is done.

Meanwhile, I added the `nilness` linter in [this](https://github.com/erigontech/erigon/pull/13146) PR. It catches redundant patterns like `if err != nil` where err is always nil or err. But doesn't catch more advanced errors like `nilnesserr`.
