### ISSUE TITLE
Caplin IPv6

### ISSUE THREAD

**Issue by totoCZ** [erigontech/erigon#13207]
` [EROR] [12-21|21:10:33.700] could not start caplin                   err="failed creating sentinel listener err=IPV4 address not provided instead :: was provided"
`

Caplin should support IPv6, it should listen on dual stack and everything that can should be able to advertise both v4 and v6 addresses.

**Comment by totoCZ** [comment]
Right now torrents and Caplin don't listen on v6. I think torrents are not important. But I should be able to set/It should detect its own IPv4/IPv6 and advertise it in discv5 at least.

**Comment by Giulio2002** [comment]
can you try https://github.com/erigontech/erigon/pull/13214 and see if it fixes it
