### ISSUE TITLE
crash on caplin query

### ISSUE THREAD

**Issue by errge** [erigontech/erigon#13217]
#### System information

Erigon version: 3.0.0-alpha7

OS & Version: Linux

Commit hash: https://github.com/erigontech/erigon/commit/34714c0c25cc59587240ae7abc1c2758315254af

Erigon Command (with flags/config):
erigon --datadir ./data --prune.mode archive --http.api=eth,erigon,web3,net,debug,trace,txpool --caplin.archive --diagnostics.disabled --nat none --private.api.addr "" --beacon.api beacon,builder,config,debug,events,node,validator,lighthouse --beacon.api.port 3500 --http.port 8545 --ws --ws.port 8546 --authrpc.port 8551 --torrent.port 20202 --port 30303 --p2p.protocol 68 --p2p.allowed-ports 30303 --caplin.discovery.tcpport 40404 --caplin.discovery.port 40404 --sentinel.port 50505 --rpc.batch.limit 50000 --db.read.concurrency 8 --rpc.returndata.limit 100000000000

Consensus Layer: builtin caplin

Consensus Layer Command (with flags/config): no other config specified than in the erigon commandline

Chain/Network: ethereum mainnet

#### Expected behaviour

No crash on any kind of query.

#### Actual behaviour

Something in my query pipeline triggers the backtrace below.

#### Steps to reproduce the behaviour

Still didn't nail down the actual query, sorry, working on it.

Hoping the backtrace in itself is useful for debugging, if not, I will report back, when I have the query that triggers the issue.

#### Backtrace

````
[INFO] [12-23|15:20:52.940] [txpool] stat                            pending=1616 baseFee=30000 queued=7918 alloc=12.6GB sys=31.7GB
[INFO] [12-23|15:21:02.387] P2P                                      app=caplin peers=36
[INFO] [12-23|15:21:13.256] [sync] limited big jump                  from=21465730 amount=5000
panic: runtime error: makeslice: len out of range

goroutine 7409878 [running]:
github.com/erigontech/erigon/cl/phase1/core/state.(*CachingBeaconState).decodeActiveValidatorsCache(0xc13b944000, {0x33d46e0, 0xc4cafb4330}, {0xc25882e260, 0x8, 0x8})
        github.com/erigontech/erigon/cl/phase1/core/state/cache.go:498 +0x27a
github.com/erigontech/erigon/cl/phase1/core/state.(*CachingBeaconState).DecodeCaches(0xc13b944000, {0x33d46e0, 0xc4cafb4330})
        github.com/erigontech/erigon/cl/phase1/core/state/cache.go:361 +0x6b
github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph.(*forkGraphDisk).readBeaconStateFromDisk(0xc23f364008, {0x73, 0x4, 0x3e, 0x87, 0x92, 0x85, 0x5a, 0x68, 0xe9, ...}, ...)
        github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph/fork_graph_disk_fs.go:102 +0xb98
github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph.(*forkGraphDisk).getState(0xc23f364008, {0x73, 0x4, 0x3e, 0x87, 0x92, 0x85, 0x5a, 0x68, 0xe9, ...}, ...)
        github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph/fork_graph_disk.go:381 +0x23e
github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph.(*forkGraphDisk).GetState(0x137e17526076567a?, {0x73, 0x4, 0x3e, 0x87, 0x92, 0x85, 0x5a, 0x68, 0xe9, ...}, ...)
        github.com/erigontech/erigon/cl/phase1/forkchoice/fork_graph/fork_graph_disk.go:339 +0x28
github.com/erigontech/erigon/cl/phase1/forkchoice.(*ForkChoiceStore).GetStateAtBlockRoot(0xbf15e79aff0afe6d?, {0x73, 0x4, 0x3e, 0x87, 0x92, 0x85, 0x5a, 0x68, 0xe9, ...}, ...)
        github.com/erigontech/erigon/cl/phase1/forkchoice/forkchoice.go:361 +0xdd
github.com/erigontech/erigon/cl/phase1/stages.postForkchoiceOperations({0x33f4268, 0xc1d5edee60}, {0x3427540, 0xc42db70dc0}, {0x340a668, 0xc13b7ba880}, 0xc2561e21e0, 0xa2f000, {0x73, 0x4, ...})
        github.com/erigontech/erigon/cl/phase1/stages/forkchoice.go:299 +0x9f
github.com/erigontech/erigon/cl/phase1/stages.doForkchoiceRoutine({0x33f4268, 0xc1d5edee60}, {0x340a668, 0xc13b7ba880}, 0xc2561e21e0, {0x27, 0x51780, 0x51781, 0xa2f020, 0xa2f020, ...})
        github.com/erigontech/erigon/cl/phase1/stages/forkchoice.go:365 +0x30e
github.com/erigontech/erigon/cl/clstages.(*StageGraph[...]).StartWithStage.func1()
        github.com/erigontech/erigon/cl/clstages/clstages.go:54 +0x6e
created by github.com/erigontech/erigon/cl/clstages.(*StageGraph[...]).StartWithStage in goroutine 32545
        github.com/erigontech/erigon/cl/clstages/clstages.go:50 +0x3a5
````

**Comment by errge** [comment]
```
while curl -s localhost:3500/eth/v1/beacon/states/finalized/validators/12345 >/dev/null ; do date ; sleep 1; done
```

Managed to reproduce this issue.  Running this triggers the crash every ~20-30 minutes.

**Comment by Giulio2002** [comment]
ok this seems like some form of low memory. is there more details? is something happening in the meantime?

**Comment by Giulio2002** [comment]
how much RAM do you have? I see `alloc=12.6GB sys=31.7GB`. if you have only `32 GB` then this happens due to low memory

**Comment by errge** [comment]
It's not low memory, I have 64G and alpha3 routinely consumed up to 50G without issues.  Also, the issue is clearly triggered by the query flow, if I stop the queries, there are no/less crashes.

**Comment by AskAlexSharov** [comment]
try: `ERIGON_SAVE_HEAP_PROFILE=true ERIGON_HEAP_PROFILE_FILE_PATH=/path/to/some/dir` it will save erigon's mem profile when erigon will eat > 45% of RAM.
