### ISSUE TITLE
Erigon3 should prune blobs

### ISSUE THREAD

**Issue by tornadocontrib** [erigontech/erigon#13242]
Currently Erigon3 doesn't prune blobs with flag `--prune.mode="archive" --caplin.backfilling.blob="true"`.

Blobs are short living data and only 2 week span data should remain on disk when pruning is not disabled by flag.

Otherwise it is likely that those short living data would overcome the size of historic states and blocks.

**Comment by Giulio2002** [comment]
this is expected behaviour as `--caplin.backfilling.blob="true"` is used for DA on L2 nodes. you cannot sync one without them
