### ISSUE TITLE
Please support parity_listStorageKeys

### ISSUE THREAD

**Issue by ytrezq** [erigontech/erigon#2028]
Returns the full blockchain of a specific contract at any block being requested.

Is actually used by various tools like [Pakala](https://github.com/palkeo/pakala). On OpenEthereum it requires fatdb to be enabled on the database.

**Comment by AlexeyAkhunov** [comment]
How do you use it? With `latest` block or for historical blocks too? I am asking because it is much easier to implement it for `latest` block

**Comment by AlexeyAkhunov** [comment]
Though for historical blocks, we may take the same approach as `debug_getStorageRangeAt`

**Comment by ytrezq** [comment]
The main point of parity_listStorageKeys is for past storagelisting.
Since it requires the fatdb feature in Openethereum, should we conclude it would also need database changes in Erigon too?

**Comment by ytrezq** [comment]
@AlexeyAkhunov @AndreaLanfranchi any chance a compatibility breaking change in the Erigon database would be accepted or is reopening https://github.com/openethereum the only way out to support building token rich lists on past blocks?

**Comment by ytrezq** [comment]
Can this be made a priority again?

**Comment by AskAlexSharov** [comment]
let's take a look

**Comment by ytrezq** [comment]
@AlexeyAkhunov why?
