### ISSUE TITLE
Switch to MatchPrefixCmp method

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#7855]
Long time ago we added deocompress.go:MatchPrefix func, but it did return `bool` instead of `-1, 0 1` (which required for binary-search of .bt index). 
Then we added MatchPrefixCmp func to address this issue. 
Then we added MatchPrefixUncompressed func for faster navigate - if user knows that word is not compressed. 

My idea:
1. replace MatchPrefix by MatchPrefixCmp and remove MatchPrefix
2. `ArchiveGetter` must provide MatchPrefixCmp func (with auto-switch to MatchPrefixUncompressed under the hood)
3. `BtIndex.keyCmp` must use MatchPrefixCmp func instead of batch

Then in future we can use `BtIndex` on top of compressed `.kv` file.

Ensure that we have enough tests on `MatchPrefixCmp` 
Resolve all `TODO` in MatchPrefixCmp/MatchPrefixUncompressed methods

**Comment by racytech** [comment]
what is requestKey?
