### ISSUE TITLE
eth_call stateDiff incompatible with geth and other clients.

### ISSUE THREAD

**Issue by ape-dev-cs** [erigontech/erigon#8345]
When calling eth_call with a 3rd parameter / stateDiff, Erigon errors out with a format that geth accepts, and geth errors when you give it a format that Erigon accepts. I've only reproduced this as a consumer of Erigon over various 3rd party APIs, however I've reproduced it on mainnet and gnosis chain, across several providers which offer Erigon as an option.

Geth expects padded hex, but Erigon wants unpadded hex.

The following stateDiff format will work for Geth, but if you change the URL to an Erigon endpoint, you'll get `invalid argument 2: hex number with leading zero digits`

```bash
curl --location '<geth rpc url>' \
--header 'Content-Type: application/json' \
--data '{"method":"eth_call","params":[
  {
    "to": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    "data": "0x70a08231000000000000000000000000cee284f754e854890e311e3280b767f80797180d"
  },
  "latest",
  {
    "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48": {
      "stateDiff": {
        "0xe662039a65ca5042e7bf9cd555c85673904cb7f77f060e9932ce299a47545319": "0x000000000000000000000000000000000000000000000000000000003b9aca00"
      }
    }
  }
],"id":50,"jsonrpc":"2.0"}'
```

Conversely, if you hit Erigon with the following (identical but with statediff value zero pading removed), you'll get a correct response:
```bash
curl --location '<erigon rpc url>' \
--header 'Content-Type: application/json' \
--data '{"method":"eth_call","params":[
  {
    "to": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    "data": "0x70a08231000000000000000000000000cee284f754e854890e311e3280b767f80797180d"
  },
  "latest",
  {
    "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48": {
      "stateDiff": {
        "0xe662039a65ca5042e7bf9cd555c85673904cb7f77f060e9932ce299a47545319": "0x3b9aca00"
      }
    }
  }
],"id":50,"jsonrpc":"2.0"}'
```

But if you fire this request at Geth, you get `invalid argument 2: hex string has length 8, want 64 for common.Hash`

Root cause of this seems to be `Account.State` and `Account.StateDiff` in [api.go](https://github.com/ledgerwatch/erigon/blob/devel/turbo/adapter/ethapi/api.go#L171) being implemented as map of Hash -> uint64, rather than in geth's implementation [where it's a map of Hash -> Hash](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L947).

I'm guessing this could be fixed with either more permissive marshalling/unmarshalling, or changing the underlying type, but I don't want to submit a PR until I've had some guidance from someone more experienced with the codebase.

**Comment by soos3d** [comment]
This is affecting debug_traceCall as well.

**Comment by AskAlexSharov** [comment]
fixed by https://github.com/erigontech/erigon/pull/10531 and https://github.com/erigontech/erigon/pull/10531
