### ISSUE TITLE
`eth_syncing` returns `false` when syncing

### ISSUE THREAD

**Issue by shunsukew** [erigontech/erigon#8360]
#### System information

Erigon version: `./erigon --version`
`erigon version 2.49.2-stable`

OS & Version: Windows/Linux/OSX
`Linux`

Erigon Command (with flags/config):
```
/usr/local/bin/erigon --chain=sepolia \
  --identity=beaver-dev-ba2bd1c4 \
  --datadir=/data/sepolia \
  --torrent.download.rate=20mb \
  --maxpeers 15 \
  --private.api.addr=localhost:9090 \
  --metrics.addr=0.0.0.0 \
  --metrics.port=6060 \
  --pprof \
  --pprof.addr=0.0.0.0 \
  --pprof.port=6061 \
  --internalcl
```

Concensus Layer:
- Internal CL (Caplin)
- Also, with Lighthouse, encountering the same

Concensus Layer Command (with flags/config):
```
/usr/local/bin/lighthouse bn --network=sepolia \
  --datadir=/data/lighthouse \
  --http \
  --http-port 5052 \
  --execution-endpoint http://localhost:8551 \
  --execution-jwt /data/erigon/jwt.hex \
  --checkpoint-sync-url https://checkpoint-sync.sepolia.ethpandaops.io \
  --disable-deposit-contract-sync \
  --target-peers 15
```

Chain/Network: Sepolia

#### Expected behaviour
As defined [RPC API spec](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_syncing), `eth_syncing` should return syncing status (e.g. `currentBlock`, `highestBlock `).

#### Actual behaviour
API returns `false` even though the node is still syncing.

#### Steps to reproduce the behaviour
`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_syncing", "params": [], "id":1}' $NODE_ENDPONT`

<img width="1455" alt="Screen Shot 2023-10-04 at 13 52 50" src="https://github.com/ledgerwatch/erigon/assets/28953860/aff5a007-8ada-440e-9723-0ede6b0c4e07">

**Comment by mbwmbw1337** [comment]
I believe this only happens *after* the initial sync, i.e. if you sync once reach the chain head then fall behind and re-sync it'll show as false. I have observed the same behaviour you are reporting.

**Comment by shunsukew** [comment]
I see, I just started new node process from 0 block and now getting below response.
Please let me see after some time again.
<img width="1512" alt="Screen Shot 2023-10-11 at 12 29 33" src="https://github.com/ledgerwatch/erigon/assets/28953860/54ee94ee-80fa-4dd7-b46f-ca34962d655c">

> I believe this only happens after the initial sync, i.e. if you sync once reach the chain head then fall behind and re-sync it'll show as false. I have observed the same behaviour you are reporting.

I see, response is expected to be syncing status whenever node is syncing blocks (not reaching to the top).
This should be remained as an issue ticket, I will update info once finding something new. Thank you.

**Comment by shunsukew** [comment]
Even if the node hasn't reached to the chain head once, RPC returns `false` when still syncing blocks.
<img width="1512" alt="Screen Shot 2023-10-13 at 12 22 45" src="https://github.com/ledgerwatch/erigon/assets/28953860/d85d6b1e-c3c4-469e-99c6-2effa5edc122">

**Comment by Giulio2002** [comment]
fixed in Erigon 3
