### ISSUE TITLE
Docker hub `stable` tag not updated

### ISSUE THREAD

**Issue by yorickdowne** [erigontech/erigon#8453]
#### Issue

The `stable` tag for `thorax/erigon` on Docker Hub was last pushed 1 month ago.

If it has been deprecated, this should probably be documented in the project's `docker-compose.yml`; if it is still meant to be available, having it keep step with Erigon releases sounds good.

**Comment by michelemodolo** [comment]
Assigning to you @lystopad

**Comment by yperbasis** [comment]
Instead of `thorax/erigon:stable`, we now have `erigontech/erigon:latest`, which is updated when release input parameter `publish_latest_tag` is set to true (introduced by PR #11775).
