### ISSUE TITLE
Erigon program crashes and exits unexpectedly.  Exception 0xc0000005 0x8 0x0 0x0 PC=0x0 signal arrived during external code execution

### ISSUE THREAD

**Issue by lucyzhang314** [erigontech/erigon#8460]
#### System information

Erigon version: `./erigon --version`

erigon version 2.52.1 
erigon version 2.52.4

OS & Version: Windows/Linux/OSX

Windows 23H2 Build 25967

Commit hash: 
N/A
Erigon Command (with flags/config):

erigon.exe --datadir .

Concensus Layer:  
N/A

Concensus Layer Command (with flags/config): 
N/A

Chain/Network:  
Mainnet

#### Expected behaviour
N/A

#### Actual behaviour
INFO[10-13|10:59:08.212] logging to file system                   log dir=logs file prefix=erigon log level=info json=false
INFO[10-13|10:59:08.219] Build info                               git_branch= git_tag= git_commit=
INFO[10-13|10:59:08.219] Starting Erigon on Ethereum mainnet...
INFO[10-13|10:59:08.220] Maximum peer count                       ETH=100 total=100
INFO[10-13|10:59:08.220] starting HTTP APIs                       APIs=eth,erigon,engine
INFO[10-13|10:59:08.220] torrent verbosity                        level=WRN
INFO[10-13|10:59:10.346] Set global gas cap                       cap=50000000
INFO[10-13|10:59:10.367] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=16mb upload.rate=4mb
INFO[10-13|10:59:10.369] Opening Database                         label=chaindata path=D:\\erigon\\chaindata
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

runtime.cgocall(0x2bb8cd0, 0xc000614388)
        /usr/local/go/src/runtime/cgocall.go:157 +0x4a fp=0xc000614360 sp=0xc000614328 pc=0xfd544a
github.com/erigontech/mdbx-go/mdbx._Cfunc_mdbx_env_create(0xc000aa4660)
        _cgo_gotypes.go:643 +0x52 fp=0xc000614388 sp=0xc000614360 pc=0x134f992
github.com/erigontech/mdbx-go/mdbx.NewEnv.func1(0xc000aa4660)
        /root/go/pkg/mod/github.com/erigontech/mdbx-go@v0.27.17/mdbx/env.go:137 +0x46 fp=0xc0006143b8 sp=0xc000614388 pc=0x1354086
github.com/erigontech/mdbx-go/mdbx.NewEnv()
        /root/go/pkg/mod/github.com/erigontech/mdbx-go@v0.27.17/mdbx/env.go:137 +0x2f fp=0xc0006143e8 sp=0xc0006143b8 pc=0x1353f4f
github.com/ledgerwatch/erigon-lib/kv/mdbx.MdbxOpts.Open({{0x3f8a558, 0xc0000c4660}, 0xc000e1c000, 0x3c56b58, {0xc001424240, 0x13}, 0x0, 0x30000000000, 0x1000000, 0xffffffffffffffff, ...})
        /go/src/github.com/ledgerwatch/erigon/erigon-lib/kv/mdbx/kv_mdbx.go:238 +0x305 fp=0xc000614860 sp=0xc0006143e8 pc=0x1c3adc5
github.com/ledgerwatch/erigon/node.OpenDatabase.func1(0x0)
        /go/src/github.com/ledgerwatch/erigon/node/node.go:366 +0x7e5 fp=0xc0006150b8 sp=0xc000614860 pc=0x24f54c5
github.com/ledgerwatch/erigon/node.OpenDatabase(0xc001423000, 0x0, {0x0?, 0x0?}, 0x0, {0x3f8a558, 0xc0000c4660})
        /go/src/github.com/ledgerwatch/erigon/node/node.go:369 +0x2f7 fp=0xc0006151a0 sp=0xc0006150b8 pc=0x24f49d7
github.com/ledgerwatch/erigon/eth.New(0xc0003f2070, 0xc000e2ee00, {0x3f8a558, 0xc0000c4660})
        /go/src/github.com/ledgerwatch/erigon/eth/backend.go:232 +0x48c fp=0xc000617828 sp=0xc0006151a0 pc=0x2b8f82c
github.com/ledgerwatch/erigon/turbo/node.New({0x3f77c18?, 0xc000052170?}, 0x3f8a558?, 0xc0000c4660?, {0x3f8a558, 0xc0000c4660})
        /go/src/github.com/ledgerwatch/erigon/turbo/node/node.go:122 +0xa5 fp=0xc000617888 sp=0xc000617828 pc=0x2ba0a45
main.runErigon(0xc000e17c80)
        /go/src/github.com/ledgerwatch/erigon/cmd/erigon/main.go:80 +0x445 fp=0xc000617ae8 sp=0xc000617888 pc=0x2bb5dc5
github.com/ledgerwatch/erigon/turbo/app.MakeApp.func1(0xc000e17c80)
        /go/src/github.com/ledgerwatch/erigon/turbo/app/make_app.go:43 +0xc2 fp=0xc000617be8 sp=0xc000617ae8 pc=0x2baa9a2
github.com/urfave/cli/v2.(*Command).Run(0xc0008ba2c0, 0xc000e17c80, {0xc00018a000, 0x8, 0x8})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x9eb fp=0xc000617e88 sp=0xc000617be8 pc=0x14d588b
github.com/urfave/cli/v2.(*App).RunContext(0xc000314d20, {0x3f77c18?, 0xc000052170}, {0xc00018a000, 0x8, 0x8})
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x616 fp=0xc000617ef8 sp=0xc000617e88 pc=0x14d21b6
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main()
        /go/src/github.com/ledgerwatch/erigon/cmd/erigon/main.go:41 +0x8f fp=0xc000617f80 sp=0xc000617ef8 pc=0x2bb588f
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x1f7 fp=0xc000617fe0 sp=0xc000617f80 pc=0x100f9f7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000617fe8 sp=0xc000617fe0 pc=0x1042401

#### Backtrace

````
[backtrace]
````

**Comment by AskAlexSharov** [comment]
is it start on empty datadir? or on existing one? 
hotfix: remove datadir/nodes folder

**Comment by JABirchall** [comment]
Im getting this as well. Erigon just fails to launch.

Something is broken in mdbx which is whats causing this stack error. 

go-mdbx is causing an access violation on windows.

**Comment by AskAlexSharov** [comment]
@JABirchall 
do you start on empty datadir? or on existing one?
removing of datadir/nodes folder - helps you?

**Comment by JABirchall** [comment]
The specific requirements for mingw and gcc does make it difficult to build on my machine. 
If the only requirement was go and cgo then i could build it and debug the issue myself.

**Comment by kaliubuntu0206** [comment]
For anyone having the issue, make sure that you have the latest GCC compiler installed via mingw, default mingw-w64 from internet will install you the older one, so I recommend you to check out https://github.com/niXman/mingw-builds-binaries/releases or the chocolatey manager.

**Comment by AskAlexSharov** [comment]
yes. at-least this versions: https://github.com/erigontech/erigon/blob/main/.github/workflows/test-integration.yml#L63
