### ISSUE TITLE
SIGBUS: bus error erigon

### ISSUE THREAD

**Issue by Mrigesh901** [erigontech/erigon#9260]
#### System information

Erigon version: `erigon version 2.55.1-12889fd0`

OS & Version: Linux Ubuntu 22.04

Erigon Command (with flags/config):  /usr/local/bin/erigon --chain=gnosis --datadir=/home/gnosis/execution/datadir/ --authrpc.jwtsecret=/home/gnosis/jwtsecret/jwt.hex --ws --http.addr="0.0.0.0" --metrics --port=30303 --http.port=8545 --torrent.upload.rate="512mb" --torrent.download.rate="512mb" --http.api="eth,admin,debug,net,trace,web3,erigon" --http.vhosts *

Consensus Layer: Lighthouse

Consensus Layer Command (with flags/config): /usr/local/bin/lighthouse --network gnosis beacon_node --datadir=/home/gnosis/consensus/datadir --http --execution-endpoint http://localhost:8551 --execution-jwt /home/gnosis/jwtsecret/jwt.hex --checkpoint-sync-url "https://checkpoint.gnosischain.com"

Chain/Network: gnosis

#### Actual behaviour

![image](https://github.com/ledgerwatch/erigon/assets/59439845/5b67bc07-3fdd-4723-a2ac-971ec786c3f7)

Integration logs:

![image](https://github.com/ledgerwatch/erigon/assets/59439845/45d269ca-7e63-4a01-8b81-02912821124b)

#### Backtrace

````
[backtrace]
````

**Comment by yperbasis** [comment]
Please re-open is this happens with erigon v2.60.10 or later.
