### ISSUE TITLE
cl/fork tests have `time.Now()` dependency in them

### ISSUE THREAD

**Issue by jyellick** [erigontech/erigon#9400]
#### System information

Commit hash:  114baa0f5c972997b2946e5bb85ff5c1bbda6253

https://github.com/ledgerwatch/erigon/blob/114baa0f5c972997b2946e5bb85ff5c1bbda6253/cl/fork/fork.go#L105

#### Expected behaviour

If a build passes CI, or a local `make test`, then re-running that same procedure a second time (in the same environment) should succeed.

#### Actual behaviour

Because the digests in `fork_test.go` are static, but the time is not, these tests will eventually begin to fail as time elapses: e.g.

https://github.com/ledgerwatch/erigon/blob/114baa0f5c972997b2946e5bb85ff5c1bbda6253/cl/fork/fork_test.go#L69

#### Steps to reproduce the behaviour

Check out an older version of Erigon, and run the tests for example:

```
$ git checkout v2.57.0
$ go test ./cl/fork/
--- FAIL: TestSepoliaForkDigest (0.00s)
    fork_test.go:69: 
        	Error Trace:	/home/yellickj/oss/erigon/cl/fork/fork_test.go:69
        	Error:      	Not equal: 
        	           	expected: [4]uint8{0x47, 0xeb, 0x72, 0xb3}
        	           	actual  : [4]uint8{0xd3, 0x1f, 0x61, 0x91}
        	           	
        	           	Diff:
        	           	--- Expected
        	           	+++ Actual
        	           	@@ -1,3 +1,3 @@
        	           	([4]uint8) (len=4) {
        	           	- 00000000  47 eb 72 b3                                       |G.r.|
        	           	+ 00000000  d3 1f 61 91                                       |..a.|
        	           	}
        	Test:       	TestSepoliaForkDigest
FAIL
FAIL	github.com/ledgerwatch/erigon/cl/fork	0.146s
FAIL
```

#### Suggested remediation

These functions should be modified to optionally take in the current time as a parameter, or perhaps a mock time service can be supplied.  Anything that removes the dependency on the real clock time for the tests.

If there is a consensus on the right way to fix this, I'm happy to implement and submit a PR.

**Comment by Giulio2002** [comment]
this will happen once per hard fork and it is a decent test for network. i can live with this.
