### ISSUE TITLE
Unexpected behavior on Polygon when calling `eth_getBlockByNumber` with the real block number.

### ISSUE THREAD

**Issue by blockjoe** [erigontech/erigon#9826]
#### System information

Erigon version: erigon version 2.58.2-125509e4

#### Expected behaviour

When trying to retrieve a block near the head via the `rpcdaemon` directly by it's block number, we expect to actually get back the block:

```bash
curl --request POST \
  --url <url> \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
  "jsonrpc": "2.0",
  "method": "eth_blockNumber",
  "params": [],
  "id": 0
}'
{
  "id": 0,
  "jsonrpc": "2.0",
  "result": "0x123456"
}
```

```bash
curl --request POST \
  --url <rpc-url> \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
  "jsonrpc": "2.0",
  "method": "eth_getBlockByNumber",
  "params": [
    "0x123456",
    false
  ],
  "id": 0
}'
{
  "id": 0,
  "jsonrpc": "2.0",
  "result": {
      "parentHash": "0xabcdef",
       "sha3Uncles": "0xfedcba",
       ...
}  
```

#### Actual behaviour

We're instead seeing 1 of 4 behaviors:

1. We receive a JSON-RPC response that has a null result, i.e:

```json
{
  "id": 0,
  "jsonrpc": "2.0",
  "result": null,
}
```

2. We receive the following error:

```json
{
  "id": 0,
  "jsonrpc": "2.0",
  "error": {
    "code": -32000,
    "message": "rlp: end of list"
  },
```

3. The connection times out while the node remains unresponsive.

4. We can successfully retrieve the block.

#### Steps to reproduce the behaviour

Make multiple lookups for blocks by their actual number instead of `"latest"` when that block number is either the current `"latest"` block, or close to it.

**Comment by antonis19** [comment]
@blockjoe Could you try upgrading to `v2.60.5` and see if you still get the same problem?
